using System;

namespace MediationModel
{
    public interface ICdr
    {
         int SwitchId { get; set; }
         long idcall { get; set; }
         long SequenceNumber { get; set; }
         string FileName { get; set; }
         int ServiceGroup { get; set; }
         string incomingroute { get; set; }
         string OriginatingIP { get; set; }
         Nullable<int> OPC { get; set; }
         Nullable<int> OriginatingCIC { get; set; }
         string OriginatingCalledNumber { get; set; }
         string TerminatingCalledNumber { get; set; }
         string OriginatingCallingNumber { get; set; }
         string TerminatingCallingNumber { get; set; }
         Nullable<byte> PrePaid { get; set; }
         decimal DurationSec { get; set; }
         DateTime EndTime { get; set; }
         Nullable<DateTime> ConnectTime { get; set; }
         Nullable<DateTime> AnswerTime { get; set; }
         Nullable<byte> ChargingStatus { get; set; }
         Nullable<Single> PDD { get; set; }
         string CountryCode { get; set; }
         Nullable<int> AreaCodeOrLata { get; set; }
         Nullable<byte> ReleaseDirection { get; set; }
         Nullable<int> ReleaseCauseSystem { get; set; }
         Nullable<int> ReleaseCauseEgress { get; set; }
         string outgoingroute { get; set; }
         string TerminatingIP { get; set; }
         Nullable<int> DPC { get; set; }
         Nullable<int> TerminatingCIC { get; set; }
         DateTime StartTime { get; set; }
         Nullable<int> inPartnerId { get; set; }
        Nullable<decimal> CustomerRate { get; set; }
        Nullable<int> outPartnerId { get; set; }
         Nullable<decimal> SupplierRate { get; set; }
         string MatchedPrefixY { get; set; }
         Nullable<decimal> USDRateY { get; set; }
         string matchedprefixcustomer { get; set; }
         string matchedprefixsupplier { get; set; }
         Nullable<decimal> CustomerCost { get; set; }
         Nullable<decimal> SupplierCost { get; set; }
         Nullable<decimal> CostANSIn { get; set; }
         Nullable<decimal> CostICXIn { get; set; }
         Nullable<decimal> Tax1 { get; set; }
         Nullable<decimal> IGWRevenueIn { get; set; }
         Nullable<decimal> RevenueANSOut { get; set; }
         Nullable<decimal> RevenueIGWOut { get; set; }
         Nullable<decimal> RevenueICXOut { get; set; }
         Nullable<decimal> Tax2 { get; set; }
         Nullable<decimal> SubscriberChargeXOut { get; set; }
         Nullable<decimal> CarrierCostYIGWOut { get; set; }
         string ANSPrefixOrig { get; set; }
         Nullable<int> AnsIdOrig { get; set; }
         string AnsPrefixTerm { get; set; }
         Nullable<int> AnsIdTerm { get; set; }
         Nullable<int> validflag { get; set; }
         Nullable<sbyte> PartialFlag { get; set; }
         Nullable<int> releasecauseingress { get; set; }
         Nullable<long> CustomerCallNumberANS { get; set; }
         Nullable<long> SupplierCallNumberANS { get; set; }
         Nullable<byte> CalledPartyNOA { get; set; }
         Nullable<byte> CallingPartyNOA { get; set; }
         Nullable<long> AdditionalSystemCodes { get; set; }
         Nullable<byte> AdditionalPartyNumber { get; set; }
         Nullable<int> ResellerIds { get; set; }
         Nullable<decimal> BTRCTermRate { get; set; }
         Nullable<int> PreviousRoutes { get; set; }
         Nullable<int> E1Id { get; set; }
         string MediaIP1 { get; set; }
         string MediaIP2 { get; set; }
         string MediaIP3 { get; set; }
         string MediaIP4 { get; set; }
         Nullable<decimal> CallCancelDuration { get; set; }
         Nullable<int> E1IdOut { get; set; }
         string inTrunkAdditionalInfo { get; set; }
         string outTrunkAdditionalInfo { get; set; }
         string inMgwId { get; set; }
         string outMgwId { get; set; }
         Nullable<sbyte> mediationcomplete { get; set; }
         string codec { get; set; }
         Nullable<byte> ConnectedNumberType { get; set; }
         string RedirectingNumber { get; set; }
         Nullable<byte> CallForwardOrRoamingType { get; set; }
         Nullable<DateTime> date1 { get; set; }
         Nullable<int> field1 { get; set; }
         Nullable<int> field2 { get; set; }
         Nullable<int> field3 { get; set; }
         string errorCode { get; set; }
         Nullable<int> field5 { get; set; }
         Nullable<decimal> roundedduration { get; set; }
         Nullable<decimal> PartialDuration { get; set; }
         Nullable<DateTime> PartialAnswerTime { get; set; }
         Nullable<DateTime> PartialEndTime { get; set; }
         Nullable<long> FinalRecord { get; set; }
         Nullable<decimal> Duration1 { get; set; }
         Nullable<decimal> Duration2 { get; set; }
         Nullable<decimal> Duration3 { get; set; }
         Nullable<decimal> Duration4 { get; set; }
         Nullable<int> PreviousPeriodCdr { get; set; }
         string UniqueBillId { get; set; }
         string AdditionalMetaData { get; set; }
         Nullable<int> Category { get; set; }
         Nullable<int> SubCategory { get; set; }
         Nullable<long> ChangedByJobId { get; set; }
         DateTime ActualStartTime { get; set; }
    }
}
