//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_prev_transaction
    {
        public long transactionId { get; set; }
        public string uniqueBillInfo { get; set; }
        public long idEvent { get; set; }
        public System.DateTime transactionTime { get; set; }
        public Nullable<sbyte> assignedDirection { get; set; }
        public string description { get; set; }
        public long postingAccountId { get; set; }
        public int servicegroup { get; set; }
        public int servicefamily { get; set; }
        public long ProductId { get; set; }
        public string idBilledUom { get; set; }
        public string idQuantityUom { get; set; }
        public double BilledAmount { get; set; }
        public double Quantity { get; set; }
        public double unitPriceOrCharge { get; set; }
        public string Prefix { get; set; }
        public long RateId { get; set; }
        public Nullable<double> TaxAmount1 { get; set; }
        public Nullable<double> TaxAmount2 { get; set; }
        public Nullable<double> TaxAmount3 { get; set; }
        public Nullable<double> VatAmount1 { get; set; }
        public Nullable<double> VatAmount2 { get; set; }
        public Nullable<double> VatAmount3 { get; set; }
        public Nullable<double> OtherAmount1 { get; set; }
        public Nullable<double> OtherAmount2 { get; set; }
        public Nullable<double> OtherAmount3 { get; set; }
        public Nullable<long> createdByJob { get; set; }
        public Nullable<long> changedByJob { get; set; }
        public string jsonDetail { get; set; }
        public sbyte isBillable { get; set; }
    }
}
