//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_balance
    {
        public long idAccount { get; set; }
        public double BalanceBefore { get; set; }
        public Nullable<double> lastAmount { get; set; }
        public double BalanceAfter { get; set; }
        public System.DateTime lastUpdated { get; set; }
    
        public virtual account account { get; set; }
    }
}
