//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_temp_transaction
    {
        public long id { get; set; }
        public System.DateTime transactionTime { get; set; }
        public Nullable<short> seqId { get; set; }
        public string debitOrCredit { get; set; }
        public long idEvent { get; set; }
        public string uniqueBillId { get; set; }
        public string description { get; set; }
        public long glAccountId { get; set; }
        public string uomId { get; set; }
        public decimal amount { get; set; }
        public decimal BalanceBefore { get; set; }
        public decimal BalanceAfter { get; set; }
        public Nullable<sbyte> isBillable { get; set; }
        public Nullable<sbyte> isPrepaid { get; set; }
        public Nullable<sbyte> isBilled { get; set; }
        public Nullable<sbyte> cancelled { get; set; }
        public Nullable<long> createdByJob { get; set; }
        public Nullable<long> changedByJob { get; set; }
        public string jsonDetail { get; set; }
    }
}
