//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public long id { get; set; }
        public Nullable<long> idParent { get; set; }
        public string idParentExternal { get; set; }
        public int idPartner { get; set; }
        public string accountName { get; set; }
        public string iduom { get; set; }
        public int Depth { get; set; }
        public string Lineage { get; set; }
        public string remark { get; set; }
    
        public virtual acc_balance acc_balance { get; set; }
    }
}
