//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class billingruleassignment
    {
        public int idRatePlanAssignmentTuple { get; set; }
        public Nullable<int> idBillingRule { get; set; }
    
        public virtual jsonbillingrule jsonbillingrule { get; set; }
        public virtual rateplanassignmenttuple rateplanassignmenttuple { get; set; }
    }
}
