//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class causecode
    {
        public int id { get; set; }
        public int idSwitch { get; set; }
        public int CC { get; set; }
        public string Description { get; set; }
        public Nullable<int> CallCompleteIndicator { get; set; }
    }
}
