//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdr
    {
        public int SwitchId { get; set; }
        public long idcall { get; set; }
        public long SequenceNumber { get; set; }
        public string FileName { get; set; }
        public Nullable<byte> CallDirection { get; set; }
        public string incomingroute { get; set; }
        public string OriginatingIP { get; set; }
        public Nullable<int> OPC { get; set; }
        public Nullable<int> OriginatingCIC { get; set; }
        public string OriginatingCalledNumber { get; set; }
        public string TerminatingCalledNumber { get; set; }
        public string OriginatingCallingNumber { get; set; }
        public string TerminatingCallingNumber { get; set; }
        public Nullable<byte> CustomerPrePaid { get; set; }
        public double DurationSec { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<System.DateTime> ConnectTime { get; set; }
        public Nullable<System.DateTime> AnswerTime { get; set; }
        public Nullable<byte> ChargingStatus { get; set; }
        public Nullable<double> PDD { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> MinuteID { get; set; }
        public Nullable<byte> ReleaseDirection { get; set; }
        public Nullable<int> ReleaseCauseSystem { get; set; }
        public Nullable<int> ReleaseCauseEgress { get; set; }
        public string outgoingroute { get; set; }
        public string TerminatingIP { get; set; }
        public Nullable<int> DPC { get; set; }
        public Nullable<int> TerminatingCIC { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<double> CustomerRate { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<double> SupplierRate { get; set; }
        public string MatchedPrefixY { get; set; }
        public Nullable<double> USDRateY { get; set; }
        public string matchedprefixcustomer { get; set; }
        public string matchedprefixsupplier { get; set; }
        public Nullable<double> CustomerCost { get; set; }
        public Nullable<double> SupplierCost { get; set; }
        public Nullable<double> CostANSIn { get; set; }
        public Nullable<double> CostICXIn { get; set; }
        public Nullable<double> CostVATCommissionIn { get; set; }
        public Nullable<double> IGWRevenueIn { get; set; }
        public Nullable<double> RevenueANSOut { get; set; }
        public Nullable<double> RevenueIGWOut { get; set; }
        public Nullable<double> RevenueICXOut { get; set; }
        public Nullable<double> RevenueVATCommissionOut { get; set; }
        public Nullable<double> SubscriberChargeXOut { get; set; }
        public Nullable<double> CarrierCostYIGWOut { get; set; }
        public string ANSPrefixOrig { get; set; }
        public Nullable<int> AnsIdOrig { get; set; }
        public string AnsPrefixTerm { get; set; }
        public Nullable<int> AnsIdTerm { get; set; }
        public Nullable<int> validflag { get; set; }
        public Nullable<sbyte> PartialFlag { get; set; }
        public Nullable<int> releasecauseingress { get; set; }
        public Nullable<long> CustomerCallNumberANS { get; set; }
        public Nullable<long> SupplierCallNumberANS { get; set; }
        public Nullable<byte> CalledPartyNOA { get; set; }
        public Nullable<byte> CallingPartyNOA { get; set; }
        public Nullable<long> GrpDayId { get; set; }
        public Nullable<byte> MonthId { get; set; }
        public Nullable<int> DayId { get; set; }
        public Nullable<double> BTRCTermRate { get; set; }
        public Nullable<int> WeekDayId { get; set; }
        public Nullable<int> E1Id { get; set; }
        public string MediaIP1 { get; set; }
        public string MediaIP2 { get; set; }
        public string MediaIP3 { get; set; }
        public string MediaIP4 { get; set; }
        public Nullable<double> CallCancelDuration { get; set; }
        public Nullable<int> E1IdOut { get; set; }
        public Nullable<int> hourid { get; set; }
        public Nullable<int> halfhourid { get; set; }
        public Nullable<sbyte> FifteenMinutesId { get; set; }
        public Nullable<sbyte> FiveMinutesId { get; set; }
        public Nullable<sbyte> mediationcomplete { get; set; }
        public Nullable<long> TempTransactionId { get; set; }
        public Nullable<byte> ConnectedNumberType { get; set; }
        public string RedirectingNumber { get; set; }
        public Nullable<byte> CallForwardOrRoamingType { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public Nullable<int> field1 { get; set; }
        public Nullable<int> field2 { get; set; }
        public Nullable<int> field3 { get; set; }
        public string field4 { get; set; }
        public Nullable<int> field5 { get; set; }
        public Nullable<double> roundedduration { get; set; }
        public Nullable<double> PartialDuration { get; set; }
        public Nullable<System.DateTime> PartialAnswerTime { get; set; }
        public Nullable<System.DateTime> PartialEndTime { get; set; }
        public Nullable<long> FinalRecord { get; set; }
        public Nullable<double> Duration1 { get; set; }
        public Nullable<double> Duration2 { get; set; }
        public Nullable<double> Duration3 { get; set; }
        public Nullable<double> Duration4 { get; set; }
        public Nullable<int> PreviousPeriodCdr { get; set; }
        public string UniqueBillId { get; set; }
        public string BillngInfo { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> SubCategory { get; set; }
        public Nullable<long> ChangedByJobId { get; set; }
        public System.DateTime ActualStartTime { get; set; }
    }
}
