//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdrdiscarded
    {
        public string SwitchId { get; set; }
        public string idcall { get; set; }
        public string SequenceNumber { get; set; }
        public string FileName { get; set; }
        public string CallDirection { get; set; }
        public string incomingroute { get; set; }
        public string OriginatingIP { get; set; }
        public string OPC { get; set; }
        public string OriginatingCIC { get; set; }
        public string OriginatingCalledNumber { get; set; }
        public string TerminatingCalledNumber { get; set; }
        public string OriginatingCallingNumber { get; set; }
        public string TerminatingCallingNumber { get; set; }
        public string CustomerPrePaid { get; set; }
        public string DurationSec { get; set; }
        public string EndTime { get; set; }
        public string ConnectTime { get; set; }
        public string AnswerTime { get; set; }
        public string ChargingStatus { get; set; }
        public string PDD { get; set; }
        public string CountryCode { get; set; }
        public string MinuteID { get; set; }
        public string ReleaseDirection { get; set; }
        public string ReleaseCauseSystem { get; set; }
        public string ReleaseCauseEgress { get; set; }
        public string outgoingroute { get; set; }
        public string TerminatingIP { get; set; }
        public string DPC { get; set; }
        public string TerminatingCIC { get; set; }
        public string StartTime { get; set; }
        public string CustomerID { get; set; }
        public string CustomerRate { get; set; }
        public string SupplierID { get; set; }
        public string SupplierRate { get; set; }
        public string MatchedPrefixY { get; set; }
        public string USDRateY { get; set; }
        public string matchedprefixcustomer { get; set; }
        public string matchedprefixsupplier { get; set; }
        public string CustomerCost { get; set; }
        public string SupplierCost { get; set; }
        public string CostANSIn { get; set; }
        public string CostICXIn { get; set; }
        public string CostVATCommissionIn { get; set; }
        public string IGWRevenueIn { get; set; }
        public string RevenueANSOut { get; set; }
        public string RevenueIGWOut { get; set; }
        public string RevenueICXOut { get; set; }
        public string RevenueVATCommissionOut { get; set; }
        public string SubscriberChargeXOut { get; set; }
        public string CarrierCostYIGWOut { get; set; }
        public string ANSPrefixOrig { get; set; }
        public string AnsIdOrig { get; set; }
        public string AnsPrefixTerm { get; set; }
        public string AnsIdTerm { get; set; }
        public string validflag { get; set; }
        public string PartialFlag { get; set; }
        public string releasecauseingress { get; set; }
        public string CustomerCallNumberANS { get; set; }
        public string SupplierCallNumberANS { get; set; }
        public string CalledPartyNOA { get; set; }
        public string CallingPartyNOA { get; set; }
        public string GrpDayId { get; set; }
        public string MonthId { get; set; }
        public string DayId { get; set; }
        public string BTRCTermRate { get; set; }
        public string WeekDayId { get; set; }
        public string E1Id { get; set; }
        public string MediaIP1 { get; set; }
        public string MediaIP2 { get; set; }
        public string MediaIP3 { get; set; }
        public string MediaIP4 { get; set; }
        public string CallCancelDuration { get; set; }
        public string E1IdOut { get; set; }
        public string hourid { get; set; }
        public string halfhourid { get; set; }
        public string FifteenMinutesId { get; set; }
        public string FiveMinutesId { get; set; }
        public string mediationcomplete { get; set; }
        public string TempTransactionId { get; set; }
        public string ConnectedNumberType { get; set; }
        public string RedirectingNumber { get; set; }
        public string CallForwardOrRoamingType { get; set; }
        public string date1 { get; set; }
        public string field1 { get; set; }
        public string field2 { get; set; }
        public string field3 { get; set; }
        public string field4 { get; set; }
        public string field5 { get; set; }
        public string roundedduration { get; set; }
        public string PartialDuration { get; set; }
        public string PartialAnswerTime { get; set; }
        public string PartialEndTime { get; set; }
        public string FinalRecord { get; set; }
        public string Duration1 { get; set; }
        public string Duration2 { get; set; }
        public string Duration3 { get; set; }
        public string Duration4 { get; set; }
        public string PreviousPeriodCdr { get; set; }
        public string UniqueBillId { get; set; }
        public string BillngInfo { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string ChangedByJobId { get; set; }
        public string ActualStartTime { get; set; }
    }
}
