//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdrdiscarded
    {
        public string SwitchId { get; set; }
        public string IdCall { get; set; }
        public long SequenceNumber { get; set; }
        public string FileName { get; set; }
        public string ServiceGroup { get; set; }
        public string IncomingRoute { get; set; }
        public string OriginatingIP { get; set; }
        public string OPC { get; set; }
        public string OriginatingCIC { get; set; }
        public string OriginatingCalledNumber { get; set; }
        public string TerminatingCalledNumber { get; set; }
        public string OriginatingCallingNumber { get; set; }
        public string TerminatingCallingNumber { get; set; }
        public string PrePaid { get; set; }
        public string DurationSec { get; set; }
        public string EndTime { get; set; }
        public string ConnectTime { get; set; }
        public string AnswerTime { get; set; }
        public string ChargingStatus { get; set; }
        public string PDD { get; set; }
        public string CountryCode { get; set; }
        public string AreaCodeOrLata { get; set; }
        public string ReleaseDirection { get; set; }
        public string ReleaseCauseSystem { get; set; }
        public string ReleaseCauseEgress { get; set; }
        public string OutgoingRoute { get; set; }
        public string TerminatingIP { get; set; }
        public string DPC { get; set; }
        public string TerminatingCIC { get; set; }
        public string StartTime { get; set; }
        public string InPartnerId { get; set; }
        public string CustomerRate { get; set; }
        public string OutPartnerId { get; set; }
        public string SupplierRate { get; set; }
        public string MatchedPrefixY { get; set; }
        public string UsdRateY { get; set; }
        public string MatchedPrefixCustomer { get; set; }
        public string MatchedPrefixSupplier { get; set; }
        public string InPartnerCost { get; set; }
        public string OutPartnerCost { get; set; }
        public string CostAnsIn { get; set; }
        public string CostIcxIn { get; set; }
        public string Tax1 { get; set; }
        public string IgwRevenueIn { get; set; }
        public string RevenueAnsOut { get; set; }
        public string RevenueIgwOut { get; set; }
        public string RevenueIcxOut { get; set; }
        public string Tax2 { get; set; }
        public string XAmount { get; set; }
        public string YAmount { get; set; }
        public string AnsPrefixOrig { get; set; }
        public string AnsIdOrig { get; set; }
        public string AnsPrefixTerm { get; set; }
        public string AnsIdTerm { get; set; }
        public string ValidFlag { get; set; }
        public string PartialFlag { get; set; }
        public string ReleaseCauseIngress { get; set; }
        public string InRoamingOpId { get; set; }
        public string OutRoamingOpId { get; set; }
        public string CalledPartyNOA { get; set; }
        public string CallingPartyNOA { get; set; }
        public string AdditionalSystemCodes { get; set; }
        public string AdditionalPartyNumber { get; set; }
        public string ResellerIds { get; set; }
        public string ZAmount { get; set; }
        public string PreviousRoutes { get; set; }
        public string E1Id { get; set; }
        public string MediaIp1 { get; set; }
        public string MediaIp2 { get; set; }
        public string MediaIp3 { get; set; }
        public string MediaIp4 { get; set; }
        public string CallReleaseDuration { get; set; }
        public string E1IdOut { get; set; }
        public string InTrunkAdditionalInfo { get; set; }
        public string OutTrunkAdditionalInfo { get; set; }
        public string InMgwId { get; set; }
        public string OutMgwId { get; set; }
        public string MediationComplete { get; set; }
        public string Codec { get; set; }
        public string ConnectedNumberType { get; set; }
        public string RedirectingNumber { get; set; }
        public string CallForwardOrRoamingType { get; set; }
        public string OtherDate { get; set; }
        public string SummaryMetaTotal { get; set; }
        public string TransactionMetaTotal { get; set; }
        public string ChargeableMetaTotal { get; set; }
        public string ErrorCode { get; set; }
        public string NERSuccess { get; set; }
        public string RoundedDuration { get; set; }
        public string PartialDuration { get; set; }
        public string PartialAnswerTime { get; set; }
        public string PartialEndTime { get; set; }
        public string FinalRecord { get; set; }
        public string Duration1 { get; set; }
        public string Duration2 { get; set; }
        public string Duration3 { get; set; }
        public string Duration4 { get; set; }
        public string PreviousPeriodCdr { get; set; }
        public string UniqueBillId { get; set; }
        public string AdditionalMetaData { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string ChangedByJobId { get; set; }
        public string SignalingStartTime { get; set; }
    }
}
