//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdrfieldmappingbyswitchtype
    {
        public int Id { get; set; }
        public int FieldNumber { get; set; }
        public int idCdrFormat { get; set; }
        public Nullable<int> FieldPositionInCDRRow { get; set; }
        public Nullable<float> BinByteOffset { get; set; }
        public Nullable<float> BinByteLen { get; set; }
        public string BinByteType { get; set; }
    
        public virtual cdrfieldlist cdrfieldlist { get; set; }
    }
}
