//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdrpartialreference
    {
        public string UniqueBillId { get; set; }
        public int switchid { get; set; }
        public long lastIdcall { get; set; }
        public System.DateTime CallDate { get; set; }
        public string commaSepIdcallsForAllInstances { get; set; }
        public string lastFilename { get; set; }
    }
}
