//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class decimal_test
    {
        public int id { get; set; }
        public double double1 { get; set; }
        public double double2 { get; set; }
        public decimal decimal1 { get; set; }
        public decimal decimal2 { get; set; }
        public double doubletotal { get; set; }
        public decimal decimalTotal { get; set; }
    }
}
