//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class enuminvoicetemplate
    {
        public int id { get; set; }
        public string TemplateName { get; set; }
        public string Description { get; set; }
        public Nullable<int> json { get; set; }
        public string OtherInfo { get; set; }
    }
}
