//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobsegment
    {
        public long id { get; set; }
        public long idJob { get; set; }
        public int segmentNumber { get; set; }
        public int stepsCount { get; set; }
        public Nullable<int> status { get; set; }
        public string SegmentDetail { get; set; }
    
        public virtual job job { get; set; }
    }
}
