//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class ledger_summary_meta
    {
        public int id { get; set; }
        public decimal totalInsertedAmount { get; set; }
        public decimal totalDeletedAmount { get; set; }
    }
}
