//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jslEntities : DbContext
    {
        public jslEntities()
            : base("name=jslEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<rate> rates { get; set; }
        public virtual DbSet<cdrfieldlist> cdrfieldlists { get; set; }
        public virtual DbSet<cdr> cdrs { get; set; }
    }
}
