//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnerprefix
    {
        public int id { get; set; }
        public int idPartner { get; set; }
        public int PrefixType { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> CommonTG { get; set; }
        public Nullable<int> tier { get; set; }
    }
}
