//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class process
    {
        public int id { get; set; }
        public string ProcessName { get; set; }
        public Nullable<System.DateTime> LastRun { get; set; }
        public string ProcessParamaterJson { get; set; }
        public int AdminState { get; set; }
    }
}
