//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class rateplanassignmenttuple
    {
        public int id { get; set; }
        public long idService { get; set; }
        public int AssignDirection { get; set; }
        public Nullable<int> idpartner { get; set; }
        public Nullable<int> route { get; set; }
        public int priority { get; set; }
        public Nullable<int> tier { get; set; }
    
        public virtual billingruleassignment billingruleassignment { get; set; }
    }
}
