//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class sum_voice_hr_03
    {
        public long id { get; set; }
        public int tup_switchid { get; set; }
        public int tup_inpartnerid { get; set; }
        public int tup_outpartnerid { get; set; }
        public string tup_incomingroute { get; set; }
        public string tup_outgoingroute { get; set; }
        public double tup_customerrate { get; set; }
        public double tup_supplierrate { get; set; }
        public string tup_incomingip { get; set; }
        public string tup_outgoingip { get; set; }
        public string tup_countryorareacode { get; set; }
        public string tup_matchedprefixcustomer { get; set; }
        public string tup_matchedprefixsupplier { get; set; }
        public string tup_sourceId { get; set; }
        public string tup_destinationId { get; set; }
        public string tup_customercurrency { get; set; }
        public string tup_suppliercurrency { get; set; }
        public string tup_tax1currency { get; set; }
        public string tup_tax2currency { get; set; }
        public string tup_vatcurrency { get; set; }
        public System.DateTime tup_starttime { get; set; }
        public Nullable<long> totalcalls { get; set; }
        public Nullable<long> connectedcalls { get; set; }
        public Nullable<long> connectedcallsCC { get; set; }
        public Nullable<long> successfulcalls { get; set; }
        public Nullable<double> actualduration { get; set; }
        public Nullable<double> roundedduration { get; set; }
        public Nullable<double> duration1 { get; set; }
        public Nullable<double> duration2 { get; set; }
        public Nullable<double> duration3 { get; set; }
        public Nullable<double> PDD { get; set; }
        public Nullable<double> customercost { get; set; }
        public Nullable<double> suppliercost { get; set; }
        public Nullable<double> tax1 { get; set; }
        public Nullable<double> tax2 { get; set; }
        public Nullable<double> vat { get; set; }
        public Nullable<int> intAmount1 { get; set; }
        public Nullable<int> intAmount2 { get; set; }
        public Nullable<int> longAmount1 { get; set; }
        public Nullable<int> longAmount2 { get; set; }
        public Nullable<double> doubleAmount1 { get; set; }
        public Nullable<double> doubleAmount2 { get; set; }
    }
}
