//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class telcobrightpartner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public telcobrightpartner()
        {
            this.nes = new HashSet<ne>();
        }
    
        public int idCustomer { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> idOperatorType { get; set; }
        public string databasename { get; set; }
        public string databasetype { get; set; }
        public string user { get; set; }
        public string pass { get; set; }
        public string ServerNameOrIP { get; set; }
        public string IBServerNameOrIP { get; set; }
        public string IBdatabasename { get; set; }
        public string IBdatabasetype { get; set; }
        public string IBuser { get; set; }
        public string IBpass { get; set; }
        public Nullable<int> TransactionSizeForCDRLoading { get; set; }
        public int NativeTimeZone { get; set; }
        public string IgwPrefix { get; set; }
        public int RateDictionaryMaxRecords { get; set; }
        public float MinMSForIntlOut { get; set; }
        public int RawCdrKeepDurationDays { get; set; }
        public int SummaryKeepDurationDays { get; set; }
        public int AutoDeleteOldData { get; set; }
        public Nullable<float> AutoDeleteStartHour { get; set; }
        public Nullable<float> AutoDeleteEndHour { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ne> nes { get; set; }
    }
}
