//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class uom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uom()
        {
            this.uom_conversion_dated = new HashSet<uom_conversion_dated>();
            this.uom_conversion_dated1 = new HashSet<uom_conversion_dated>();
            this.uom_conversion = new HashSet<uom_conversion>();
            this.uom_conversion1 = new HashSet<uom_conversion>();
        }
    
        public string UOM_ID { get; set; }
        public string UOM_TYPE_ID { get; set; }
        public string ABBREVIATION { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_STAMP { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_TX_STAMP { get; set; }
        public Nullable<System.DateTime> CREATED_STAMP { get; set; }
        public Nullable<System.DateTime> CREATED_TX_STAMP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uom_conversion_dated> uom_conversion_dated { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uom_conversion_dated> uom_conversion_dated1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uom_conversion> uom_conversion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uom_conversion> uom_conversion1 { get; set; }
    }
}
