delete from btrc_cas.cdrfieldmappingbyswitchtype where idcdrformat=68;
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (0,  68,0,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (1,  68,1,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (2,  68,2,0,4,'unsigned long');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (3,  68,3,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (4,  68,4,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (5,  68,5,77,2,'unsigned short');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (6,  68,6,232,4,'ip address');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (7,  68,7,367,4,'unsigned long');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (8,  68,8,167,2,'unsigned short');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (9,  68,9,279,16,'bcd');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (10, 68,10,103,16,'bcd');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (11, 68,11,260,16,'bcd');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (12, 68,12,30,16,'bcd');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (13, 68,13,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (14, 68,14,23,4,'unsigned long');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (15, 68,15,17,6,'unsigned char');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (16, 68,16,609,6,'unsigned char');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (17, 68,17,11,6,'unsigned char');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (18, 68,18,171.375,0.125,'unsigned char');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (19, 68,19,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (20, 68,20,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (21, 68,21,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (22, 68,22,85.5,0.5,'unsigned char');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (23, 68,23,87,1,'unsigned char');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (24, 68,24,515,2,'unsigned short');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (25, 68,25,79,2,'unsigned short');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (26, 68,26,240,4,'ip address');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (27, 68,27,371,4,'unsigned long');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (28, 68,28,169,2,'unsigned short');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (29, 68,29,387,6,'unsigned char');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (30, 68,30,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (31, 68,31,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (32, 68,32,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (33, 68,33,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (34, 68,34,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (35, 68,35,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (36, 68,36,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (37, 68,37,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (38, 68,38,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (39, 68,39,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (40, 68,40,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (41, 68,41,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (42, 68,42,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (43, 68,43,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (44, 68,44,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (45, 68,45,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (46, 68,46,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (47, 68,47,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (48, 68,48,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (49, 68,49,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (50, 68,50,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (51, 68,51,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (52, 68,52,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (53, 68,53,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (54, 68,54,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (55, 68,55,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (56, 68,56,87,1,'unsigned char');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (57, 68,57,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (58, 68,58,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (59, 68,59,48,1,'unsigned char');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (60, 68,60,29,1,'unsigned char');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (61, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (62, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (63, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (64, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (65, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (66, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (67, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (68, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (69, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (70, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (71, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (72, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (73, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (74, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (75, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (76, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (77, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (78, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (79, 68,79,508,0.25,'unsigned char');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (80, 68,80,540,16,'bcd');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (81, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (82, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (83, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (84, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (85, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (86, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (87, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (88, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (89, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (90, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (91, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (92, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (93, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (94, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (95, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (96, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (97, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (98, 68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (99, 68,99,NULL,NULL,'int');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (100,68,100,NULL,NULL,'int');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (101,68,101,NULL,NULL,'int');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (102,68,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (103,68,NULL,NULL,NULL,NULL);
