using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using LibraryExtensions;
using MediationModel;
using TelcobrightMediation.Mediation.Cdr;

namespace Jobs
{
    public static class DebugCdrHelper
    {
        public static string getCreateTableSqlIfNotExists(string tableName)
        {
            return $@"CREATE TABLE if not exists {tableName} (
                  SwitchId varchar(100)  NOT NULL,
                  IdCall bigint(20) NOT NULL,
                  SequenceNumber varchar(100)  DEFAULT NULL,
                  FileName varchar(100)  NOT NULL,
                  ServiceGroup varchar(100)  DEFAULT NULL,
                  IncomingRoute varchar(100)  DEFAULT NULL,
                  originatingip varchar(100)  DEFAULT NULL,
                  OPC varchar(100)  DEFAULT NULL,
                  OriginatingCIC varchar(100)  DEFAULT NULL,
                  OriginatingCalledNumber varchar(100)  DEFAULT NULL,
                  TerminatingCalledNumber varchar(100)  DEFAULT NULL,
                  OriginatingCallingNumber varchar(100)  DEFAULT NULL,
                  TerminatingCallingNumber varchar(100)  DEFAULT NULL,
                  PrePaid varchar(100)  DEFAULT NULL,
                  DurationSec varchar(100)  DEFAULT NULL,
                  EndTime varchar(100)  DEFAULT NULL,
                  ConnectTime varchar(100)  DEFAULT NULL,
                  AnswerTime varchar(100)  DEFAULT NULL,
                  ChargingStatus varchar(100)  DEFAULT NULL,
                  PDD varchar(100)  DEFAULT NULL,
                  CountryCode varchar(100)  DEFAULT NULL,
                  AreaCodeOrLata varchar(100)  DEFAULT NULL,
                  ReleaseDirection varchar(100)  DEFAULT NULL,
                  ReleaseCauseSystem varchar(100)  DEFAULT NULL,
                  ReleaseCauseEgress varchar(100)  DEFAULT NULL,
                  OutgoingRoute varchar(100)  DEFAULT NULL,
                  terminatingip varchar(100)  DEFAULT NULL,
                  DPC varchar(100)  DEFAULT NULL,
                  TerminatingCIC varchar(100)  DEFAULT NULL,
                  StartTime datetime DEFAULT NULL,
                  InPartnerId varchar(100)  DEFAULT '0',
                  CustomerRate varchar(100)  DEFAULT NULL,
                  OutPartnerId varchar(100)  DEFAULT '0',
                  SupplierRate varchar(100)  DEFAULT NULL,
                  MatchedPrefixY varchar(100)  DEFAULT NULL,
                  UsdRateY varchar(100)  DEFAULT NULL,
                  MatchedPrefixCustomer varchar(100)  DEFAULT NULL,
                  MatchedPrefixSupplier varchar(100)  DEFAULT NULL,
                  InPartnerCost varchar(100)  DEFAULT NULL,
                  OutPartnerCost varchar(100)  DEFAULT NULL,
                  CostAnsIn varchar(100)  DEFAULT NULL,
                  CostIcxIn varchar(100)  DEFAULT NULL,
                  Tax1 varchar(100)  DEFAULT '0.00000000',
                  IgwRevenueIn varchar(100)  DEFAULT NULL,
                  RevenueAnsOut varchar(100)  DEFAULT NULL,
                  RevenueIgwOut varchar(100)  DEFAULT NULL,
                  RevenueIcxOut varchar(100)  DEFAULT NULL,
                  Tax2 varchar(100)  DEFAULT '0.00000000',
                  XAmount varchar(100)  DEFAULT NULL,
                  YAmount varchar(100)  DEFAULT NULL,
                  AnsPrefixOrig varchar(100)  DEFAULT NULL,
                  AnsIdOrig varchar(100)  DEFAULT NULL,
                  AnsPrefixTerm varchar(100)  DEFAULT NULL,
                  AnsIdTerm varchar(100)  DEFAULT NULL,
                  ValidFlag varchar(100)  DEFAULT NULL,
                  PartialFlag varchar(100)  DEFAULT NULL,
                  ReleaseCauseIngress varchar(100)  DEFAULT NULL,
                  InRoamingOpId varchar(100)  DEFAULT NULL,
                  OutRoamingOpId varchar(100)  DEFAULT NULL,
                  CalledPartyNOA varchar(100)  DEFAULT NULL,
                  CallingPartyNOA varchar(100)  DEFAULT NULL,
                  AdditionalSystemCodes varchar(100)  DEFAULT NULL,
                  AdditionalPartyNumber varchar(100)  DEFAULT NULL,
                  ResellerIds varchar(100)  DEFAULT NULL,
                  ZAmount varchar(100)  DEFAULT NULL,
                  PreviousRoutes varchar(100)  DEFAULT NULL,
                  E1Id varchar(100)  DEFAULT NULL,
                  MediaIp1 varchar(100)  DEFAULT NULL,
                  MediaIp2 varchar(100)  DEFAULT NULL,
                  MediaIp3 varchar(100)  DEFAULT NULL,
                  MediaIp4 varchar(100)  DEFAULT NULL,
                  CallReleaseDuration varchar(100)  DEFAULT NULL,
                  E1IdOut varchar(100)  DEFAULT NULL,
                  InTrunkAdditionalInfo varchar(100)  DEFAULT NULL,
                  OutTrunkAdditionalInfo varchar(100)  DEFAULT NULL,
                  InMgwId varchar(100)  DEFAULT NULL,
                  OutMgwId varchar(100)  DEFAULT NULL,
                  MediationComplete varchar(100)  DEFAULT '0',
                  Codec varchar(100)  DEFAULT NULL,
                  ConnectedNumberType varchar(100)  DEFAULT NULL,
                  RedirectingNumber varchar(100)  DEFAULT NULL,
                  CallForwardOrRoamingType varchar(100)  DEFAULT NULL,
                  OtherDate varchar(100)  DEFAULT NULL,
                  SummaryMetaTotal varchar(100)  DEFAULT NULL,
                  TransactionMetaTotal varchar(100)  DEFAULT NULL,
                  ChargeableMetaTotal varchar(100)  DEFAULT NULL,
                  ErrorCode varchar(100)  DEFAULT NULL,
                  NERSuccess varchar(100)  DEFAULT NULL,
                  RoundedDuration varchar(100)  DEFAULT NULL,
                  PartialDuration varchar(100)  DEFAULT NULL,
                  PartialAnswerTime varchar(100)  DEFAULT NULL,
                  PartialEndTime varchar(100)  DEFAULT NULL,
                  FinalRecord varchar(100)  DEFAULT NULL,
                  Duration1 varchar(100)  DEFAULT NULL,
                  Duration2 varchar(100)  DEFAULT NULL,
                  Duration3 varchar(100)  DEFAULT NULL,
                  Duration4 varchar(100)  DEFAULT NULL,
                  PreviousPeriodCdr varchar(100)  DEFAULT NULL,
                  UniqueBillId varchar(100)  DEFAULT NULL,
                  AdditionalMetaData varchar(100)  DEFAULT NULL,
                  Category varchar(100)  DEFAULT NULL,
                  SubCategory varchar(100)  DEFAULT NULL,
                  ChangedByJobId varchar(100)  DEFAULT NULL,
                  SignalingStartTime varchar(100)  DEFAULT NULL,
                  KEY ind_Unique_Bill (UniqueBillId)
                  ) ENGINE=InnoDB ";
        }
        
    }
}
