configuration: Release
os: Visual Studio 2017

version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - 2.x
services:
- mssql2016
- mysql
- postgresql
nuget:
  disable_publish_on_pr: true
build_script:
- cmd: tools\nant\bin\nant package-release -D:version.build=%APPVEYOR_BUILD_NUMBER% -D:git.hash=%APPVEYOR_REPO_COMMIT%
test: off
artifacts:
- path: Quartz.*.nupkg
  name: NuGet
- path: Quartz.NET-*.zip
  name: ZIP
