using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using LibraryExtensions;
namespace MediationModel
{
	public partial class :ICacheble<>
	{
		public string GetExtInsertValues()
		{
			return $@"(
				{column1.ToMySqlField()},
				{column2.ToMySqlField()},
				{column3.ToMySqlField()},
				{uniqueBillId.ToMySqlField()},
				{column5.ToMySqlField()},
				{column6.ToMySqlField()},
				{column7.ToMySqlField()},
				{column8.ToMySqlField()},
				{OriginatingCallingNumber.ToMySqlField()},
				{column10.ToMySqlField()},
				{column11.ToMySqlField()},
				{column12.ToMySqlField()},
				{column13.ToMySqlField()},
				{column14.ToMySqlField()},
				{column15.ToMySqlField()},
				{column16.ToMySqlField()},
				{column17.ToMySqlField()},
				{column18.ToMySqlField()},
				{column19.ToMySqlField()},
				{column20.ToMySqlField()},
				{startTime.ToMySqlField()},
				{column22.ToMySqlField()},
				{column23.ToMySqlField()},
				{column24.ToMySqlField()},
				{column25.ToMySqlField()},
				{column26.ToMySqlField()},
				{column27.ToMySqlField()},
				{column28.ToMySqlField()},
				{column29.ToMySqlField()},
				{column30.ToMySqlField()},
				{TerminatingCallingNumber.ToMySqlField()},
				{column32.ToMySqlField()},
				{column33.ToMySqlField()},
				{endTime.ToMySqlField()},
				{column35.ToMySqlField()},
				{column36.ToMySqlField()},
				{column37.ToMySqlField()},
				{column38.ToMySqlField()},
				{column39.ToMySqlField()},
				{column40.ToMySqlField()},
				{column41.ToMySqlField()},
				{column42.ToMySqlField()},
				{column43.ToMySqlField()},
				{column44.ToMySqlField()},
				{column45.ToMySqlField()},
				{column46.ToMySqlField()},
				{column47.ToMySqlField()},
				{column48.ToMySqlField()},
				{column49.ToMySqlField()},
				{answerTime.ToMySqlField()},
				{column51.ToMySqlField()},
				{column52.ToMySqlField()},
				{column53.ToMySqlField()},
				{column54.ToMySqlField()},
				{column55.ToMySqlField()},
				{column56.ToMySqlField()},
				{column57.ToMySqlField()},
				{IncomingRoute.ToMySqlField()},
				{OutgoingRoute.ToMySqlField()},
				{column60.ToMySqlField()},
				{column61.ToMySqlField()},
				{column62.ToMySqlField()},
				{column63.ToMySqlField()},
				{column64.ToMySqlField()},
				{column65.ToMySqlField()},
				{column66.ToMySqlField()},
				{column67.ToMySqlField()},
				{column68.ToMySqlField()},
				{OriginatingCalledNumber.ToMySqlField()},
				{column70.ToMySqlField()},
				{column71.ToMySqlField()},
				{column72.ToMySqlField()},
				{column73.ToMySqlField()},
				{column74.ToMySqlField()},
				{column75.ToMySqlField()},
				{column76.ToMySqlField()},
				{column77.ToMySqlField()},
				{column78.ToMySqlField()},
				{column79.ToMySqlField()},
				{TerminatingCalledNumber.ToMySqlField()},
				{column81.ToMySqlField()},
				{column82.ToMySqlField()},
				{column83.ToMySqlField()},
				{column84.ToMySqlField()},
				{column85.ToMySqlField()},
				{column86.ToMySqlField()},
				{column87.ToMySqlField()},
				{column88.ToMySqlField()},
				{column89.ToMySqlField()},
				{column90.ToMySqlField()},
				{column91.ToMySqlField()},
				{column92.ToMySqlField()},
				{column93.ToMySqlField()},
				{column94.ToMySqlField()},
				{column95.ToMySqlField()},
				{column96.ToMySqlField()},
				{column97.ToMySqlField()},
				{column98.ToMySqlField()},
				{column99.ToMySqlField()},
				{column100.ToMySqlField()},
				{column101.ToMySqlField()},
				{column102.ToMySqlField()},
				{column103.ToMySqlField()},
				{column104.ToMySqlField()},
				{column105.ToMySqlField()},
				{column106.ToMySqlField()},
				{column107.ToMySqlField()},
				{column108.ToMySqlField()},
				{column109.ToMySqlField()},
				{column110.ToMySqlField()},
				{column111.ToMySqlField()},
				{column112.ToMySqlField()},
				{column113.ToMySqlField()},
				{column114.ToMySqlField()},
				{column115.ToMySqlField()},
				{column116.ToMySqlField()},
				{column117.ToMySqlField()},
				{column118.ToMySqlField()},
				{column119.ToMySqlField()},
				{column120.ToMySqlField()},
				{column121.ToMySqlField()},
				{column122.ToMySqlField()},
				{column123.ToMySqlField()},
				{column124.ToMySqlField()},
				{column125.ToMySqlField()},
				{column126.ToMySqlField()},
				{column127.ToMySqlField()},
				{column128.ToMySqlField()},
				{column129.ToMySqlField()},
				{column130.ToMySqlField()},
				{column131.ToMySqlField()},
				{column132.ToMySqlField()},
				{column133.ToMySqlField()},
				{column134.ToMySqlField()},
				{column135.ToMySqlField()},
				{column136.ToMySqlField()},
				{duration.ToMySqlField()},
				{column138.ToMySqlField()},
				{column139.ToMySqlField()},
				{column140.ToMySqlField()},
				{column141.ToMySqlField()},
				{column142.ToMySqlField()},
				{column143.ToMySqlField()},
				{column144.ToMySqlField()},
				{column145.ToMySqlField()},
				{column146.ToMySqlField()},
				{column147.ToMySqlField()},
				{column148.ToMySqlField()},
				{column149.ToMySqlField()},
				{column150.ToMySqlField()},
				{column151.ToMySqlField()},
				{column152.ToMySqlField()},
				{column153.ToMySqlField()},
				{column154.ToMySqlField()},
				{column155.ToMySqlField()},
				{column156.ToMySqlField()},
				{column157.ToMySqlField()},
				{column158.ToMySqlField()},
				{column159.ToMySqlField()},
				{column160.ToMySqlField()},
				{column161.ToMySqlField()},
				{column162.ToMySqlField()},
				{column163.ToMySqlField()},
				{column164.ToMySqlField()},
				{column165.ToMySqlField()},
				{column166.ToMySqlField()},
				{column167.ToMySqlField()},
				{column168.ToMySqlField()},
				{column169.ToMySqlField()},
				{column170.ToMySqlField()},
				{fileName.ToMySqlField()},
				{id.ToMySqlField()}
				)";
		}
		public  string GetExtInsertCustom(Func<,string> externalInsertMethod)
		{
			return externalInsertMethod.Invoke(this);
		}
		public  string GetUpdateCommand(Func<,string> whereClauseMethod)
		{
			return $@"update dialogiccdr set 
				column1={column1.ToMySqlField()+" "},
				column2={column2.ToMySqlField()+" "},
				column3={column3.ToMySqlField()+" "},
				uniqueBillId={uniqueBillId.ToMySqlField()+" "},
				column5={column5.ToMySqlField()+" "},
				column6={column6.ToMySqlField()+" "},
				column7={column7.ToMySqlField()+" "},
				column8={column8.ToMySqlField()+" "},
				OriginatingCallingNumber={OriginatingCallingNumber.ToMySqlField()+" "},
				column10={column10.ToMySqlField()+" "},
				column11={column11.ToMySqlField()+" "},
				column12={column12.ToMySqlField()+" "},
				column13={column13.ToMySqlField()+" "},
				column14={column14.ToMySqlField()+" "},
				column15={column15.ToMySqlField()+" "},
				column16={column16.ToMySqlField()+" "},
				column17={column17.ToMySqlField()+" "},
				column18={column18.ToMySqlField()+" "},
				column19={column19.ToMySqlField()+" "},
				column20={column20.ToMySqlField()+" "},
				startTime={startTime.ToMySqlField()+" "},
				column22={column22.ToMySqlField()+" "},
				column23={column23.ToMySqlField()+" "},
				column24={column24.ToMySqlField()+" "},
				column25={column25.ToMySqlField()+" "},
				column26={column26.ToMySqlField()+" "},
				column27={column27.ToMySqlField()+" "},
				column28={column28.ToMySqlField()+" "},
				column29={column29.ToMySqlField()+" "},
				column30={column30.ToMySqlField()+" "},
				TerminatingCallingNumber={TerminatingCallingNumber.ToMySqlField()+" "},
				column32={column32.ToMySqlField()+" "},
				column33={column33.ToMySqlField()+" "},
				endTime={endTime.ToMySqlField()+" "},
				column35={column35.ToMySqlField()+" "},
				column36={column36.ToMySqlField()+" "},
				column37={column37.ToMySqlField()+" "},
				column38={column38.ToMySqlField()+" "},
				column39={column39.ToMySqlField()+" "},
				column40={column40.ToMySqlField()+" "},
				column41={column41.ToMySqlField()+" "},
				column42={column42.ToMySqlField()+" "},
				column43={column43.ToMySqlField()+" "},
				column44={column44.ToMySqlField()+" "},
				column45={column45.ToMySqlField()+" "},
				column46={column46.ToMySqlField()+" "},
				column47={column47.ToMySqlField()+" "},
				column48={column48.ToMySqlField()+" "},
				column49={column49.ToMySqlField()+" "},
				answerTime={answerTime.ToMySqlField()+" "},
				column51={column51.ToMySqlField()+" "},
				column52={column52.ToMySqlField()+" "},
				column53={column53.ToMySqlField()+" "},
				column54={column54.ToMySqlField()+" "},
				column55={column55.ToMySqlField()+" "},
				column56={column56.ToMySqlField()+" "},
				column57={column57.ToMySqlField()+" "},
				IncomingRoute={IncomingRoute.ToMySqlField()+" "},
				OutgoingRoute={OutgoingRoute.ToMySqlField()+" "},
				column60={column60.ToMySqlField()+" "},
				column61={column61.ToMySqlField()+" "},
				column62={column62.ToMySqlField()+" "},
				column63={column63.ToMySqlField()+" "},
				column64={column64.ToMySqlField()+" "},
				column65={column65.ToMySqlField()+" "},
				column66={column66.ToMySqlField()+" "},
				column67={column67.ToMySqlField()+" "},
				column68={column68.ToMySqlField()+" "},
				OriginatingCalledNumber={OriginatingCalledNumber.ToMySqlField()+" "},
				column70={column70.ToMySqlField()+" "},
				column71={column71.ToMySqlField()+" "},
				column72={column72.ToMySqlField()+" "},
				column73={column73.ToMySqlField()+" "},
				column74={column74.ToMySqlField()+" "},
				column75={column75.ToMySqlField()+" "},
				column76={column76.ToMySqlField()+" "},
				column77={column77.ToMySqlField()+" "},
				column78={column78.ToMySqlField()+" "},
				column79={column79.ToMySqlField()+" "},
				TerminatingCalledNumber={TerminatingCalledNumber.ToMySqlField()+" "},
				column81={column81.ToMySqlField()+" "},
				column82={column82.ToMySqlField()+" "},
				column83={column83.ToMySqlField()+" "},
				column84={column84.ToMySqlField()+" "},
				column85={column85.ToMySqlField()+" "},
				column86={column86.ToMySqlField()+" "},
				column87={column87.ToMySqlField()+" "},
				column88={column88.ToMySqlField()+" "},
				column89={column89.ToMySqlField()+" "},
				column90={column90.ToMySqlField()+" "},
				column91={column91.ToMySqlField()+" "},
				column92={column92.ToMySqlField()+" "},
				column93={column93.ToMySqlField()+" "},
				column94={column94.ToMySqlField()+" "},
				column95={column95.ToMySqlField()+" "},
				column96={column96.ToMySqlField()+" "},
				column97={column97.ToMySqlField()+" "},
				column98={column98.ToMySqlField()+" "},
				column99={column99.ToMySqlField()+" "},
				column100={column100.ToMySqlField()+" "},
				column101={column101.ToMySqlField()+" "},
				column102={column102.ToMySqlField()+" "},
				column103={column103.ToMySqlField()+" "},
				column104={column104.ToMySqlField()+" "},
				column105={column105.ToMySqlField()+" "},
				column106={column106.ToMySqlField()+" "},
				column107={column107.ToMySqlField()+" "},
				column108={column108.ToMySqlField()+" "},
				column109={column109.ToMySqlField()+" "},
				column110={column110.ToMySqlField()+" "},
				column111={column111.ToMySqlField()+" "},
				column112={column112.ToMySqlField()+" "},
				column113={column113.ToMySqlField()+" "},
				column114={column114.ToMySqlField()+" "},
				column115={column115.ToMySqlField()+" "},
				column116={column116.ToMySqlField()+" "},
				column117={column117.ToMySqlField()+" "},
				column118={column118.ToMySqlField()+" "},
				column119={column119.ToMySqlField()+" "},
				column120={column120.ToMySqlField()+" "},
				column121={column121.ToMySqlField()+" "},
				column122={column122.ToMySqlField()+" "},
				column123={column123.ToMySqlField()+" "},
				column124={column124.ToMySqlField()+" "},
				column125={column125.ToMySqlField()+" "},
				column126={column126.ToMySqlField()+" "},
				column127={column127.ToMySqlField()+" "},
				column128={column128.ToMySqlField()+" "},
				column129={column129.ToMySqlField()+" "},
				column130={column130.ToMySqlField()+" "},
				column131={column131.ToMySqlField()+" "},
				column132={column132.ToMySqlField()+" "},
				column133={column133.ToMySqlField()+" "},
				column134={column134.ToMySqlField()+" "},
				column135={column135.ToMySqlField()+" "},
				column136={column136.ToMySqlField()+" "},
				duration={duration.ToMySqlField()+" "},
				column138={column138.ToMySqlField()+" "},
				column139={column139.ToMySqlField()+" "},
				column140={column140.ToMySqlField()+" "},
				column141={column141.ToMySqlField()+" "},
				column142={column142.ToMySqlField()+" "},
				column143={column143.ToMySqlField()+" "},
				column144={column144.ToMySqlField()+" "},
				column145={column145.ToMySqlField()+" "},
				column146={column146.ToMySqlField()+" "},
				column147={column147.ToMySqlField()+" "},
				column148={column148.ToMySqlField()+" "},
				column149={column149.ToMySqlField()+" "},
				column150={column150.ToMySqlField()+" "},
				column151={column151.ToMySqlField()+" "},
				column152={column152.ToMySqlField()+" "},
				column153={column153.ToMySqlField()+" "},
				column154={column154.ToMySqlField()+" "},
				column155={column155.ToMySqlField()+" "},
				column156={column156.ToMySqlField()+" "},
				column157={column157.ToMySqlField()+" "},
				column158={column158.ToMySqlField()+" "},
				column159={column159.ToMySqlField()+" "},
				column160={column160.ToMySqlField()+" "},
				column161={column161.ToMySqlField()+" "},
				column162={column162.ToMySqlField()+" "},
				column163={column163.ToMySqlField()+" "},
				column164={column164.ToMySqlField()+" "},
				column165={column165.ToMySqlField()+" "},
				column166={column166.ToMySqlField()+" "},
				column167={column167.ToMySqlField()+" "},
				column168={column168.ToMySqlField()+" "},
				column169={column169.ToMySqlField()+" "},
				column170={column170.ToMySqlField()+" "},
				fileName={fileName.ToMySqlField()+" "},
				id={id.ToMySqlField()+" "}
				{whereClauseMethod.Invoke(this)};
				";
		}
		public  string GetUpdateCommandCustom(Func<,string> updateCommandMethodCustom)
		{
			return updateCommandMethodCustom.Invoke(this);
		}
		public  string GetDeleteCommand(Func<,string> whereClauseMethod)
		{
			return $@"delete from dialogiccdr 
				{whereClauseMethod.Invoke(this)};
				";
		}
	}
}
