using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using LibraryExtensions;
namespace MediationModel
{
	public partial class :ICacheble<>
	{
		public string GetExtInsertValues()
		{
			return $@"(
				{SwitchId.ToMySqlField()},
				{idCall.ToMySqlField()},
				{SequenceNumber.ToMySqlField()},
				{FileSerialNo.ToMySqlField()},
				{CallDirection.ToMySqlField()},
				{IncomingRoute.ToMySqlField()},
				{OriginatingIP.ToMySqlField()},
				{OPC.ToMySqlField()},
				{OriginatingCIC.ToMySqlField()},
				{OriginatingCalledNumber.ToMySqlField()},
				{TerminatingCalledNumber.ToMySqlField()},
				{OriginatingCallingNumber.ToMySqlField()},
				{TerminatingCallingNumber.ToMySqlField()},
				{CustomerPrePaid.ToMySqlField()},
				{DurationSec.ToMySqlField()},
				{EndTime.ToMySqlField()},
				{ConnectTime.ToMySqlField()},
				{AnswerTime.ToMySqlField()},
				{ChargingStatus.ToMySqlField()},
				{PDD.ToMySqlField()},
				{CountryCode.ToMySqlField()},
				{MinuteID.ToMySqlField()},
				{ReleaseDirection.ToMySqlField()},
				{ReleaseCauseSystem.ToMySqlField()},
				{ReleaseCauseEgress.ToMySqlField()},
				{OutgoingRoute.ToMySqlField()},
				{TerminatingIP.ToMySqlField()},
				{DPC.ToMySqlField()},
				{TerminatingCIC.ToMySqlField()},
				{StartTime.ToMySqlField()},
				{CustomerID.ToMySqlField()},
				{CustomerRate.ToMySqlField()},
				{SupplierID.ToMySqlField()},
				{SupplierRate.ToMySqlField()},
				{MatchedPrefixY.ToMySqlField()},
				{MediationRuleSupplier.ToMySqlField()},
				{MatchedPrefixCustomer.ToMySqlField()},
				{MatchedPrefixSupplier.ToMySqlField()},
				{CustomerCost.ToMySqlField()},
				{SupplierCost.ToMySqlField()},
				{CostANSIn.ToMySqlField()},
				{CostICXIn.ToMySqlField()},
				{CostVATCommissionIn.ToMySqlField()},
				{IGWRevenueIn.ToMySqlField()},
				{RevenueANSOut.ToMySqlField()},
				{RevenueIGWOut.ToMySqlField()},
				{RevenueICXOut.ToMySqlField()},
				{RevenueVATCommissionOut.ToMySqlField()},
				{SubscriberChargeXOut.ToMySqlField()},
				{CarrierCostYIGWOut.ToMySqlField()},
				{ANSPrefixOrig.ToMySqlField()},
				{AnsIdOrig.ToMySqlField()},
				{AnsPrefixTerm.ToMySqlField()},
				{AnsIdTerm.ToMySqlField()},
				{ValidFlag.ToMySqlField()},
				{PartialFlag.ToMySqlField()},
				{ReleaseCauseIngress.ToMySqlField()},
				{CustomerCallNumberANS.ToMySqlField()},
				{SupplierCallNumberANS.ToMySqlField()},
				{CalledPartyNOA.ToMySqlField()},
				{CallingPartyNOA.ToMySqlField()},
				{YearID.ToMySqlField()},
				{CalledPartyNOAOut.ToMySqlField()},
				{CallingPartyNOAOut.ToMySqlField()},
				{BTRCTermRate.ToMySqlField()},
				{WeekDayId.ToMySqlField()},
				{E1Id.ToMySqlField()},
				{MediaIP1.ToMySqlField()},
				{MediaIP2.ToMySqlField()},
				{MediaIP3.ToMySqlField()},
				{MediaIP4.ToMySqlField()},
				{CallCancelDuration.ToMySqlField()},
				{E1IdOut.ToMySqlField()},
				{inTrunkAdditionalInfo.ToMySqlField()},
				{outTrunkAdditionalInfo.ToMySqlField()},
				{InMgwId.ToMySqlField()},
				{OutMgwId.ToMySqlField()},
				{MediationComplete.ToMySqlField()},
				{Codec.ToMySqlField()},
				{ConnectedNumberType.ToMySqlField()},
				{RedirectingNumber.ToMySqlField()},
				{CallForwardOrRoamingType.ToMySqlField()},
				{date1.ToMySqlField()},
				{field1.ToMySqlField()},
				{field2.ToMySqlField()},
				{field3.ToMySqlField()},
				{field4.ToMySqlField()},
				{field5.ToMySqlField()},
				{RoundedDuration.ToMySqlField()},
				{PartialDuration.ToMySqlField()},
				{PartialAnswerTime.ToMySqlField()},
				{PartialEndTime.ToMySqlField()},
				{FinalRecord.ToMySqlField()},
				{Duration1.ToMySqlField()},
				{Duration2.ToMySqlField()},
				{Duration3.ToMySqlField()},
				{Duration4.ToMySqlField()},
				{PreviousPeriodCdr.ToMySqlField()},
				{UniqueBillId.ToMySqlField()},
				{BillingInfo.ToMySqlField()},
				{Category.ToMySqlField()},
				{SubCategory.ToMySqlField()},
				{ChangedByJobId.ToMySqlField()},
				{EventDate.ToMySqlField()}
				)";
		}
		public  string GetExtInsertCustom(Func<,string> externalInsertMethod)
		{
			return externalInsertMethod.Invoke(this);
		}
		public  string GetUpdateCommand(Func<,string> whereClauseMethod)
		{
			return $@"update mockcdr set 
				SwitchId={SwitchId.ToMySqlField()+" "},
				idCall={idCall.ToMySqlField()+" "},
				SequenceNumber={SequenceNumber.ToMySqlField()+" "},
				FileSerialNo={FileSerialNo.ToMySqlField()+" "},
				CallDirection={CallDirection.ToMySqlField()+" "},
				IncomingRoute={IncomingRoute.ToMySqlField()+" "},
				OriginatingIP={OriginatingIP.ToMySqlField()+" "},
				OPC={OPC.ToMySqlField()+" "},
				OriginatingCIC={OriginatingCIC.ToMySqlField()+" "},
				OriginatingCalledNumber={OriginatingCalledNumber.ToMySqlField()+" "},
				TerminatingCalledNumber={TerminatingCalledNumber.ToMySqlField()+" "},
				OriginatingCallingNumber={OriginatingCallingNumber.ToMySqlField()+" "},
				TerminatingCallingNumber={TerminatingCallingNumber.ToMySqlField()+" "},
				CustomerPrePaid={CustomerPrePaid.ToMySqlField()+" "},
				DurationSec={DurationSec.ToMySqlField()+" "},
				EndTime={EndTime.ToMySqlField()+" "},
				ConnectTime={ConnectTime.ToMySqlField()+" "},
				AnswerTime={AnswerTime.ToMySqlField()+" "},
				ChargingStatus={ChargingStatus.ToMySqlField()+" "},
				PDD={PDD.ToMySqlField()+" "},
				CountryCode={CountryCode.ToMySqlField()+" "},
				MinuteID={MinuteID.ToMySqlField()+" "},
				ReleaseDirection={ReleaseDirection.ToMySqlField()+" "},
				ReleaseCauseSystem={ReleaseCauseSystem.ToMySqlField()+" "},
				ReleaseCauseEgress={ReleaseCauseEgress.ToMySqlField()+" "},
				OutgoingRoute={OutgoingRoute.ToMySqlField()+" "},
				TerminatingIP={TerminatingIP.ToMySqlField()+" "},
				DPC={DPC.ToMySqlField()+" "},
				TerminatingCIC={TerminatingCIC.ToMySqlField()+" "},
				StartTime={StartTime.ToMySqlField()+" "},
				CustomerID={CustomerID.ToMySqlField()+" "},
				CustomerRate={CustomerRate.ToMySqlField()+" "},
				SupplierID={SupplierID.ToMySqlField()+" "},
				SupplierRate={SupplierRate.ToMySqlField()+" "},
				MatchedPrefixY={MatchedPrefixY.ToMySqlField()+" "},
				MediationRuleSupplier={MediationRuleSupplier.ToMySqlField()+" "},
				MatchedPrefixCustomer={MatchedPrefixCustomer.ToMySqlField()+" "},
				MatchedPrefixSupplier={MatchedPrefixSupplier.ToMySqlField()+" "},
				CustomerCost={CustomerCost.ToMySqlField()+" "},
				SupplierCost={SupplierCost.ToMySqlField()+" "},
				CostANSIn={CostANSIn.ToMySqlField()+" "},
				CostICXIn={CostICXIn.ToMySqlField()+" "},
				CostVATCommissionIn={CostVATCommissionIn.ToMySqlField()+" "},
				IGWRevenueIn={IGWRevenueIn.ToMySqlField()+" "},
				RevenueANSOut={RevenueANSOut.ToMySqlField()+" "},
				RevenueIGWOut={RevenueIGWOut.ToMySqlField()+" "},
				RevenueICXOut={RevenueICXOut.ToMySqlField()+" "},
				RevenueVATCommissionOut={RevenueVATCommissionOut.ToMySqlField()+" "},
				SubscriberChargeXOut={SubscriberChargeXOut.ToMySqlField()+" "},
				CarrierCostYIGWOut={CarrierCostYIGWOut.ToMySqlField()+" "},
				ANSPrefixOrig={ANSPrefixOrig.ToMySqlField()+" "},
				AnsIdOrig={AnsIdOrig.ToMySqlField()+" "},
				AnsPrefixTerm={AnsPrefixTerm.ToMySqlField()+" "},
				AnsIdTerm={AnsIdTerm.ToMySqlField()+" "},
				ValidFlag={ValidFlag.ToMySqlField()+" "},
				PartialFlag={PartialFlag.ToMySqlField()+" "},
				ReleaseCauseIngress={ReleaseCauseIngress.ToMySqlField()+" "},
				CustomerCallNumberANS={CustomerCallNumberANS.ToMySqlField()+" "},
				SupplierCallNumberANS={SupplierCallNumberANS.ToMySqlField()+" "},
				CalledPartyNOA={CalledPartyNOA.ToMySqlField()+" "},
				CallingPartyNOA={CallingPartyNOA.ToMySqlField()+" "},
				YearID={YearID.ToMySqlField()+" "},
				CalledPartyNOAOut={CalledPartyNOAOut.ToMySqlField()+" "},
				CallingPartyNOAOut={CallingPartyNOAOut.ToMySqlField()+" "},
				BTRCTermRate={BTRCTermRate.ToMySqlField()+" "},
				WeekDayId={WeekDayId.ToMySqlField()+" "},
				E1Id={E1Id.ToMySqlField()+" "},
				MediaIP1={MediaIP1.ToMySqlField()+" "},
				MediaIP2={MediaIP2.ToMySqlField()+" "},
				MediaIP3={MediaIP3.ToMySqlField()+" "},
				MediaIP4={MediaIP4.ToMySqlField()+" "},
				CallCancelDuration={CallCancelDuration.ToMySqlField()+" "},
				E1IdOut={E1IdOut.ToMySqlField()+" "},
				inTrunkAdditionalInfo={inTrunkAdditionalInfo.ToMySqlField()+" "},
				outTrunkAdditionalInfo={outTrunkAdditionalInfo.ToMySqlField()+" "},
				InMgwId={InMgwId.ToMySqlField()+" "},
				OutMgwId={OutMgwId.ToMySqlField()+" "},
				MediationComplete={MediationComplete.ToMySqlField()+" "},
				Codec={Codec.ToMySqlField()+" "},
				ConnectedNumberType={ConnectedNumberType.ToMySqlField()+" "},
				RedirectingNumber={RedirectingNumber.ToMySqlField()+" "},
				CallForwardOrRoamingType={CallForwardOrRoamingType.ToMySqlField()+" "},
				date1={date1.ToMySqlField()+" "},
				field1={field1.ToMySqlField()+" "},
				field2={field2.ToMySqlField()+" "},
				field3={field3.ToMySqlField()+" "},
				field4={field4.ToMySqlField()+" "},
				field5={field5.ToMySqlField()+" "},
				RoundedDuration={RoundedDuration.ToMySqlField()+" "},
				PartialDuration={PartialDuration.ToMySqlField()+" "},
				PartialAnswerTime={PartialAnswerTime.ToMySqlField()+" "},
				PartialEndTime={PartialEndTime.ToMySqlField()+" "},
				FinalRecord={FinalRecord.ToMySqlField()+" "},
				Duration1={Duration1.ToMySqlField()+" "},
				Duration2={Duration2.ToMySqlField()+" "},
				Duration3={Duration3.ToMySqlField()+" "},
				Duration4={Duration4.ToMySqlField()+" "},
				PreviousPeriodCdr={PreviousPeriodCdr.ToMySqlField()+" "},
				UniqueBillId={UniqueBillId.ToMySqlField()+" "},
				BillingInfo={BillingInfo.ToMySqlField()+" "},
				Category={Category.ToMySqlField()+" "},
				SubCategory={SubCategory.ToMySqlField()+" "},
				ChangedByJobId={ChangedByJobId.ToMySqlField()+" "},
				EventDate={EventDate.ToMySqlField()+" "}
				{whereClauseMethod.Invoke(this)};
				";
		}
		public  string GetUpdateCommandCustom(Func<,string> updateCommandMethodCustom)
		{
			return updateCommandMethodCustom.Invoke(this);
		}
		public  string GetDeleteCommand(Func<,string> whereClauseMethod)
		{
			return $@"delete from mockcdr 
				{whereClauseMethod.Invoke(this)};
				";
		}
	}
}
