using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using LibraryExtensions;
namespace MediationModel
{
	public partial class cdrpartialrawinstance:ICacheble<cdrpartialrawinstance>
	{
		public string GetExtInsertValues()
		{
			return $@"(
				{SwitchId.ToMySqlField()},
				{idcall.ToMySqlField()},
				{SequenceNumber.ToMySqlField()},
				{FileName.ToMySqlField()},
				{ServiceGroup.ToMySqlField()},
				{incomingroute.ToMySqlField()},
				{OriginatingIP.ToMySqlField()},
				{OPC.ToMySqlField()},
				{OriginatingCIC.ToMySqlField()},
				{OriginatingCalledNumber.ToMySqlField()},
				{TerminatingCalledNumber.ToMySqlField()},
				{OriginatingCallingNumber.ToMySqlField()},
				{TerminatingCallingNumber.ToMySqlField()},
				{PrePaid.ToMySqlField()},
				{DurationSec.ToMySqlField()},
				{EndTime.ToMySqlField()},
				{ConnectTime.ToMySqlField()},
				{AnswerTime.ToMySqlField()},
				{ChargingStatus.ToMySqlField()},
				{PDD.ToMySqlField()},
				{CountryCode.ToMySqlField()},
				{AreaCodeOrLata.ToMySqlField()},
				{ReleaseDirection.ToMySqlField()},
				{ReleaseCauseSystem.ToMySqlField()},
				{ReleaseCauseEgress.ToMySqlField()},
				{outgoingroute.ToMySqlField()},
				{TerminatingIP.ToMySqlField()},
				{DPC.ToMySqlField()},
				{TerminatingCIC.ToMySqlField()},
				{StartTime.ToMySqlField()},
				{inPartnerId.ToMySqlField()},
				{CustomerRate.ToMySqlField()},
				{outPartnerId.ToMySqlField()},
				{SupplierRate.ToMySqlField()},
				{MatchedPrefixY.ToMySqlField()},
				{USDRateY.ToMySqlField()},
				{matchedprefixcustomer.ToMySqlField()},
				{matchedprefixsupplier.ToMySqlField()},
				{CustomerCost.ToMySqlField()},
				{SupplierCost.ToMySqlField()},
				{CostANSIn.ToMySqlField()},
				{CostICXIn.ToMySqlField()},
				{Tax1.ToMySqlField()},
				{IGWRevenueIn.ToMySqlField()},
				{RevenueANSOut.ToMySqlField()},
				{RevenueIGWOut.ToMySqlField()},
				{RevenueICXOut.ToMySqlField()},
				{Tax2.ToMySqlField()},
				{SubscriberChargeXOut.ToMySqlField()},
				{CarrierCostYIGWOut.ToMySqlField()},
				{ANSPrefixOrig.ToMySqlField()},
				{AnsIdOrig.ToMySqlField()},
				{AnsPrefixTerm.ToMySqlField()},
				{AnsIdTerm.ToMySqlField()},
				{validflag.ToMySqlField()},
				{PartialFlag.ToMySqlField()},
				{releasecauseingress.ToMySqlField()},
				{CustomerCallNumberANS.ToMySqlField()},
				{SupplierCallNumberANS.ToMySqlField()},
				{CalledPartyNOA.ToMySqlField()},
				{CallingPartyNOA.ToMySqlField()},
				{AdditionalSystemCodes.ToMySqlField()},
				{AdditionalPartyNumber.ToMySqlField()},
				{ResellerIds.ToMySqlField()},
				{BTRCTermRate.ToMySqlField()},
				{PreviousRoutes.ToMySqlField()},
				{E1Id.ToMySqlField()},
				{MediaIP1.ToMySqlField()},
				{MediaIP2.ToMySqlField()},
				{MediaIP3.ToMySqlField()},
				{MediaIP4.ToMySqlField()},
				{CallCancelDuration.ToMySqlField()},
				{E1IdOut.ToMySqlField()},
				{inTrunkAdditionalInfo.ToMySqlField()},
				{outTrunkAdditionalInfo.ToMySqlField()},
				{inMgwId.ToMySqlField()},
				{outMgwId.ToMySqlField()},
				{mediationcomplete.ToMySqlField()},
				{codec.ToMySqlField()},
				{ConnectedNumberType.ToMySqlField()},
				{RedirectingNumber.ToMySqlField()},
				{CallForwardOrRoamingType.ToMySqlField()},
				{date1.ToMySqlField()},
				{field1.ToMySqlField()},
				{field2.ToMySqlField()},
				{field3.ToMySqlField()},
				{errorCode.ToMySqlField()},
				{field5.ToMySqlField()},
				{roundedduration.ToMySqlField()},
				{PartialDuration.ToMySqlField()},
				{PartialAnswerTime.ToMySqlField()},
				{PartialEndTime.ToMySqlField()},
				{FinalRecord.ToMySqlField()},
				{Duration1.ToMySqlField()},
				{Duration2.ToMySqlField()},
				{Duration3.ToMySqlField()},
				{Duration4.ToMySqlField()},
				{PreviousPeriodCdr.ToMySqlField()},
				{UniqueBillId.ToMySqlField()},
				{AdditionalMetaData.ToMySqlField()},
				{Category.ToMySqlField()},
				{SubCategory.ToMySqlField()},
				{ChangedByJobId.ToMySqlField()},
				{ActualStartTime.ToMySqlField()}
				)";
		}
		public  string GetExtInsertCustom(Func<cdrpartialrawinstance,string> externalInsertMethod)
		{
			return externalInsertMethod.Invoke(this);
		}
		public  string GetUpdateCommand(Func<cdrpartialrawinstance,string> whereClauseMethod)
		{
			return $@"update cdrpartialrawinstance set 
				SwitchId={SwitchId.ToMySqlField()+" "},
				idcall={idcall.ToMySqlField()+" "},
				SequenceNumber={SequenceNumber.ToMySqlField()+" "},
				FileName={FileName.ToMySqlField()+" "},
				ServiceGroup={ServiceGroup.ToMySqlField()+" "},
				incomingroute={incomingroute.ToMySqlField()+" "},
				OriginatingIP={OriginatingIP.ToMySqlField()+" "},
				OPC={OPC.ToMySqlField()+" "},
				OriginatingCIC={OriginatingCIC.ToMySqlField()+" "},
				OriginatingCalledNumber={OriginatingCalledNumber.ToMySqlField()+" "},
				TerminatingCalledNumber={TerminatingCalledNumber.ToMySqlField()+" "},
				OriginatingCallingNumber={OriginatingCallingNumber.ToMySqlField()+" "},
				TerminatingCallingNumber={TerminatingCallingNumber.ToMySqlField()+" "},
				PrePaid={PrePaid.ToMySqlField()+" "},
				DurationSec={DurationSec.ToMySqlField()+" "},
				EndTime={EndTime.ToMySqlField()+" "},
				ConnectTime={ConnectTime.ToMySqlField()+" "},
				AnswerTime={AnswerTime.ToMySqlField()+" "},
				ChargingStatus={ChargingStatus.ToMySqlField()+" "},
				PDD={PDD.ToMySqlField()+" "},
				CountryCode={CountryCode.ToMySqlField()+" "},
				AreaCodeOrLata={AreaCodeOrLata.ToMySqlField()+" "},
				ReleaseDirection={ReleaseDirection.ToMySqlField()+" "},
				ReleaseCauseSystem={ReleaseCauseSystem.ToMySqlField()+" "},
				ReleaseCauseEgress={ReleaseCauseEgress.ToMySqlField()+" "},
				outgoingroute={outgoingroute.ToMySqlField()+" "},
				TerminatingIP={TerminatingIP.ToMySqlField()+" "},
				DPC={DPC.ToMySqlField()+" "},
				TerminatingCIC={TerminatingCIC.ToMySqlField()+" "},
				StartTime={StartTime.ToMySqlField()+" "},
				inPartnerId={inPartnerId.ToMySqlField()+" "},
				CustomerRate={CustomerRate.ToMySqlField()+" "},
				outPartnerId={outPartnerId.ToMySqlField()+" "},
				SupplierRate={SupplierRate.ToMySqlField()+" "},
				MatchedPrefixY={MatchedPrefixY.ToMySqlField()+" "},
				USDRateY={USDRateY.ToMySqlField()+" "},
				matchedprefixcustomer={matchedprefixcustomer.ToMySqlField()+" "},
				matchedprefixsupplier={matchedprefixsupplier.ToMySqlField()+" "},
				CustomerCost={CustomerCost.ToMySqlField()+" "},
				SupplierCost={SupplierCost.ToMySqlField()+" "},
				CostANSIn={CostANSIn.ToMySqlField()+" "},
				CostICXIn={CostICXIn.ToMySqlField()+" "},
				Tax1={Tax1.ToMySqlField()+" "},
				IGWRevenueIn={IGWRevenueIn.ToMySqlField()+" "},
				RevenueANSOut={RevenueANSOut.ToMySqlField()+" "},
				RevenueIGWOut={RevenueIGWOut.ToMySqlField()+" "},
				RevenueICXOut={RevenueICXOut.ToMySqlField()+" "},
				Tax2={Tax2.ToMySqlField()+" "},
				SubscriberChargeXOut={SubscriberChargeXOut.ToMySqlField()+" "},
				CarrierCostYIGWOut={CarrierCostYIGWOut.ToMySqlField()+" "},
				ANSPrefixOrig={ANSPrefixOrig.ToMySqlField()+" "},
				AnsIdOrig={AnsIdOrig.ToMySqlField()+" "},
				AnsPrefixTerm={AnsPrefixTerm.ToMySqlField()+" "},
				AnsIdTerm={AnsIdTerm.ToMySqlField()+" "},
				validflag={validflag.ToMySqlField()+" "},
				PartialFlag={PartialFlag.ToMySqlField()+" "},
				releasecauseingress={releasecauseingress.ToMySqlField()+" "},
				CustomerCallNumberANS={CustomerCallNumberANS.ToMySqlField()+" "},
				SupplierCallNumberANS={SupplierCallNumberANS.ToMySqlField()+" "},
				CalledPartyNOA={CalledPartyNOA.ToMySqlField()+" "},
				CallingPartyNOA={CallingPartyNOA.ToMySqlField()+" "},
				AdditionalSystemCodes={AdditionalSystemCodes.ToMySqlField()+" "},
				AdditionalPartyNumber={AdditionalPartyNumber.ToMySqlField()+" "},
				ResellerIds={ResellerIds.ToMySqlField()+" "},
				BTRCTermRate={BTRCTermRate.ToMySqlField()+" "},
				PreviousRoutes={PreviousRoutes.ToMySqlField()+" "},
				E1Id={E1Id.ToMySqlField()+" "},
				MediaIP1={MediaIP1.ToMySqlField()+" "},
				MediaIP2={MediaIP2.ToMySqlField()+" "},
				MediaIP3={MediaIP3.ToMySqlField()+" "},
				MediaIP4={MediaIP4.ToMySqlField()+" "},
				CallCancelDuration={CallCancelDuration.ToMySqlField()+" "},
				E1IdOut={E1IdOut.ToMySqlField()+" "},
				inTrunkAdditionalInfo={inTrunkAdditionalInfo.ToMySqlField()+" "},
				outTrunkAdditionalInfo={outTrunkAdditionalInfo.ToMySqlField()+" "},
				inMgwId={inMgwId.ToMySqlField()+" "},
				outMgwId={outMgwId.ToMySqlField()+" "},
				mediationcomplete={mediationcomplete.ToMySqlField()+" "},
				codec={codec.ToMySqlField()+" "},
				ConnectedNumberType={ConnectedNumberType.ToMySqlField()+" "},
				RedirectingNumber={RedirectingNumber.ToMySqlField()+" "},
				CallForwardOrRoamingType={CallForwardOrRoamingType.ToMySqlField()+" "},
				date1={date1.ToMySqlField()+" "},
				field1={field1.ToMySqlField()+" "},
				field2={field2.ToMySqlField()+" "},
				field3={field3.ToMySqlField()+" "},
				errorCode={errorCode.ToMySqlField()+" "},
				field5={field5.ToMySqlField()+" "},
				roundedduration={roundedduration.ToMySqlField()+" "},
				PartialDuration={PartialDuration.ToMySqlField()+" "},
				PartialAnswerTime={PartialAnswerTime.ToMySqlField()+" "},
				PartialEndTime={PartialEndTime.ToMySqlField()+" "},
				FinalRecord={FinalRecord.ToMySqlField()+" "},
				Duration1={Duration1.ToMySqlField()+" "},
				Duration2={Duration2.ToMySqlField()+" "},
				Duration3={Duration3.ToMySqlField()+" "},
				Duration4={Duration4.ToMySqlField()+" "},
				PreviousPeriodCdr={PreviousPeriodCdr.ToMySqlField()+" "},
				UniqueBillId={UniqueBillId.ToMySqlField()+" "},
				AdditionalMetaData={AdditionalMetaData.ToMySqlField()+" "},
				Category={Category.ToMySqlField()+" "},
				SubCategory={SubCategory.ToMySqlField()+" "},
				ChangedByJobId={ChangedByJobId.ToMySqlField()+" "},
				ActualStartTime={ActualStartTime.ToMySqlField()+" "}
				{whereClauseMethod.Invoke(this)};
				";
		}
		public  string GetUpdateCommandCustom(Func<cdrpartialrawinstance,string> updateCommandMethodCustom)
		{
			return updateCommandMethodCustom.Invoke(this);
		}
		public  string GetDeleteCommand(Func<cdrpartialrawinstance,string> whereClauseMethod)
		{
			return $@"delete from cdrpartialrawinstance 
				{whereClauseMethod.Invoke(this)};
				";
		}
	}
}
