//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_ledger_summary
    {
        public long id { get; set; }
        public long idAccount { get; set; }
        public System.DateTime transactionDate { get; set; }
        public decimal AMOUNT { get; set; }
    }
}
