//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdrmeta
    {
        public int id { get; set; }
        public decimal totalInsertedDuration { get; set; }
        public decimal totalDeletedDuration { get; set; }
    }
}
