//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_item
    {
        public string INVOICE_ID { get; set; }
        public string INVOICE_ITEM_SEQ_ID { get; set; }
        public string INVOICE_ITEM_TYPE_ID { get; set; }
        public string OVERRIDE_GL_ACCOUNT_ID { get; set; }
        public string OVERRIDE_ORG_PARTY_ID { get; set; }
        public string INVENTORY_ITEM_ID { get; set; }
        public string PRODUCT_ID { get; set; }
        public string PRODUCT_FEATURE_ID { get; set; }
        public string PARENT_INVOICE_ID { get; set; }
        public string PARENT_INVOICE_ITEM_SEQ_ID { get; set; }
        public string UOM_ID { get; set; }
        public string TAXABLE_FLAG { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string DESCRIPTION { get; set; }
        public string TAX_AUTH_PARTY_ID { get; set; }
        public string TAX_AUTH_GEO_ID { get; set; }
        public string TAX_AUTHORITY_RATE_SEQ_ID { get; set; }
        public string SALES_OPPORTUNITY_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_STAMP { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_TX_STAMP { get; set; }
        public Nullable<System.DateTime> CREATED_STAMP { get; set; }
        public Nullable<System.DateTime> CREATED_TX_STAMP { get; set; }
    
        public virtual invoice invoice { get; set; }
    }
}
