//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class jsonbillingrule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public jsonbillingrule()
        {
            this.billingruleassignments = new HashSet<billingruleassignment>();
        }
    
        public int id { get; set; }
        public string ruleName { get; set; }
        public string description { get; set; }
        public string JsonExpression { get; set; }
        public sbyte isPrepaid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<billingruleassignment> billingruleassignments { get; set; }
    }
}
