//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class lcrrateplan
    {
        public long id { get; set; }
        public int idRatePlan { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public int JobCreated { get; set; }
    }
}
