delete from btrc_cas.cdrfieldmappingbyswitchtype where idcdrformat=51;
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (0,  51,0,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (1,  51,1,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (2,  51,2,0,4,'unsigned long');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (3,  51,3,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (4,  51,4,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (5,  51,5,77,2,'unsigned short');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (6,  51,6,232,4,'ip address');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (7,  51,7,367,4,'unsigned long');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (8,  51,8,167,2,'unsigned short');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (9,  51,9,279,16,'bcd');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (10, 51,10,103,16,'bcd');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (11, 51,11,260,16,'bcd');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (12, 51,12,30,16,'bcd');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (13, 51,13,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (14, 51,14,23,4,'unsigned long');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (15, 51,15,17,6,'unsigned char');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (16, 51,16,609,6,'unsigned char');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (17, 51,17,11,6,'unsigned char');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (18, 51,18,171.375,0.125,'unsigned char');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (19, 51,19,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (20, 51,20,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (21, 51,21,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (22, 51,22,85.5,0.5,'unsigned char');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (23, 51,23,87,1,'unsigned char');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (24, 51,24,515,2,'unsigned short');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (25, 51,25,79,2,'unsigned short');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (26, 51,26,240,4,'ip address');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (27, 51,27,371,4,'unsigned long');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (28, 51,28,169,2,'unsigned short');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (29, 51,29,387,6,'unsigned char');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (30, 51,30,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (31, 51,31,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (32, 51,32,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (33, 51,33,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (34, 51,34,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (35, 51,35,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (36, 51,36,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (37, 51,37,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (38, 51,38,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (39, 51,39,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (40, 51,40,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (41, 51,41,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (42, 51,42,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (43, 51,43,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (44, 51,44,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (45, 51,45,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (46, 51,46,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (47, 51,47,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (48, 51,48,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (49, 51,49,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (50, 51,50,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (51, 51,51,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (52, 51,52,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (53, 51,53,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (54, 51,54,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (55, 51,55,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (56, 51,56,87,1,'unsigned char');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (57, 51,57,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (58, 51,58,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (59, 51,59,48,1,'unsigned char');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (60, 51,60,29,1,'unsigned char');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (61, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (62, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (63, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (64, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (65, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (66, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (67, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (68, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (69, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (70, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (71, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (72, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (73, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (74, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (75, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (76, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (77, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (78, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (79, 51,79,508,0.25,'unsigned char');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (80, 51,80,540,16,'bcd');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (81, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (82, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (83, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (84, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (85, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (86, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (87, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (88, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (89, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (90, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (91, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (92, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (93, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (94, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (95, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (96, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (97, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (98, 51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (99, 51,99,NULL,NULL,'int');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (100,51,100,NULL,NULL,'int');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (101,51,101,NULL,NULL,'int');
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (102,51,NULL,NULL,NULL,NULL);
INSERT INTO btrc_cas.cdrfieldmappingbyswitchtype (FieldNumber,idCdrFormat,FieldPositionInCDRRow,BinByteOffset,BinByteLen,BinByteType) VALUES (103,51,NULL,NULL,NULL,NULL);
