//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelcobrightMediation.SansayWs {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.sansay.com", ConfigurationName="SansayWs.SansayWS")]
    public interface SansayWS {
        
        // CODEGEN: Generating message contract since the operation doUploadXmlFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TelcobrightMediation.SansayWs.doUploadXmlFileResponse doUploadXmlFile(TelcobrightMediation.SansayWs.doUploadXmlFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doUploadXmlFileResponse> doUploadXmlFileAsync(TelcobrightMediation.SansayWs.doUploadXmlFileRequest request);
        
        // CODEGEN: Generating message contract since the operation doReplaceLarge is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TelcobrightMediation.SansayWs.doReplaceLargeResponse doReplaceLarge(TelcobrightMediation.SansayWs.doReplaceLargeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doReplaceLargeResponse> doReplaceLargeAsync(TelcobrightMediation.SansayWs.doReplaceLargeRequest request);
        
        // CODEGEN: Generating message contract since the operation doDelete is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TelcobrightMediation.SansayWs.doDeleteResponse doDelete(TelcobrightMediation.SansayWs.doDeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doDeleteResponse> doDeleteAsync(TelcobrightMediation.SansayWs.doDeleteRequest request);
        
        // CODEGEN: Generating message contract since the operation doDeleteLarge is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TelcobrightMediation.SansayWs.doDeleteResponse doDeleteLarge(TelcobrightMediation.SansayWs.doDeleteLargeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doDeleteResponse> doDeleteLargeAsync(TelcobrightMediation.SansayWs.doDeleteLargeRequest request);
        
        // CODEGEN: Generating message contract since the operation doUpdate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TelcobrightMediation.SansayWs.doUpdateResponse doUpdate(TelcobrightMediation.SansayWs.doUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doUpdateResponse> doUpdateAsync(TelcobrightMediation.SansayWs.doUpdateRequest request);
        
        // CODEGEN: Generating message contract since the operation doUpdateLarge is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TelcobrightMediation.SansayWs.doUpdateResponse doUpdateLarge(TelcobrightMediation.SansayWs.doUpdateLargeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doUpdateResponse> doUpdateLargeAsync(TelcobrightMediation.SansayWs.doUpdateLargeRequest request);
        
        // CODEGEN: Generating message contract since the operation doDownloadXmlFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TelcobrightMediation.SansayWs.doDownloadXmlFileResponse doDownloadXmlFile(TelcobrightMediation.SansayWs.doDownloadXmlFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doDownloadXmlFileResponse> doDownloadXmlFileAsync(TelcobrightMediation.SansayWs.doDownloadXmlFileRequest request);
        
        // CODEGEN: Generating message contract since the operation doDownloadLargeXmlFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TelcobrightMediation.SansayWs.doDownloadLargeXmlFileResponse doDownloadLargeXmlFile(TelcobrightMediation.SansayWs.doDownloadLargeXmlFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doDownloadLargeXmlFileResponse> doDownloadLargeXmlFileAsync(TelcobrightMediation.SansayWs.doDownloadLargeXmlFileRequest request);
        
        // CODEGEN: Generating message contract since the operation doQueryXmlFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TelcobrightMediation.SansayWs.doQueryXmlFileResponse doQueryXmlFile(TelcobrightMediation.SansayWs.doQueryXmlFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doQueryXmlFileResponse> doQueryXmlFileAsync(TelcobrightMediation.SansayWs.doQueryXmlFileRequest request);
        
        // CODEGEN: Generating message contract since the operation doRouteLookup is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TelcobrightMediation.SansayWs.doRouteLookupResponse doRouteLookup(TelcobrightMediation.SansayWs.doRouteLookupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doRouteLookupResponse> doRouteLookupAsync(TelcobrightMediation.SansayWs.doRouteLookupRequest request);
        
        // CODEGEN: Generating message contract since the operation doRealTimeStats is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TelcobrightMediation.SansayWs.doRealTimeStatsResponse doRealTimeStats(TelcobrightMediation.SansayWs.doRealTimeStatsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doRealTimeStatsResponse> doRealTimeStatsAsync(TelcobrightMediation.SansayWs.doRealTimeStatsRequest request);
        
        // CODEGEN: Generating message contract since the operation doSystemStats is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TelcobrightMediation.SansayWs.doSystemStatsResponse doSystemStats(TelcobrightMediation.SansayWs.doSystemStatsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doSystemStatsResponse> doSystemStatsAsync(TelcobrightMediation.SansayWs.doSystemStatsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.sansay.com")]
    public partial class uploadParams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string xmlfileField;
        
        private string tableField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string xmlfile {
            get {
                return this.xmlfileField;
            }
            set {
                this.xmlfileField = value;
                this.RaisePropertyChanged("xmlfile");
            }
        }
        
        /// <remarks/>
        public string table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
                this.RaisePropertyChanged("table");
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.sansay.com")]
    public partial class uploadResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int retCodeField;
        
        private string msgField;
        
        /// <remarks/>
        public int retCode {
            get {
                return this.retCodeField;
            }
            set {
                this.retCodeField = value;
                this.RaisePropertyChanged("retCode");
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doUploadXmlFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sansay.com", Order=0)]
        public TelcobrightMediation.SansayWs.uploadParams uploadParams;
        
        public doUploadXmlFileRequest() {
        }
        
        public doUploadXmlFileRequest(TelcobrightMediation.SansayWs.uploadParams uploadParams) {
            this.uploadParams = uploadParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doUploadXmlFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sansay.com", Order=0)]
        public TelcobrightMediation.SansayWs.uploadResult uploadResult;
        
        public doUploadXmlFileResponse() {
        }
        
        public doUploadXmlFileResponse(TelcobrightMediation.SansayWs.uploadResult uploadResult) {
            this.uploadResult = uploadResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.sansay.com")]
    public partial class replaceLargeParams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] binfileField;
        
        private string tableField;
        
        private int tableIDField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] binfile {
            get {
                return this.binfileField;
            }
            set {
                this.binfileField = value;
                this.RaisePropertyChanged("binfile");
            }
        }
        
        /// <remarks/>
        public string table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
                this.RaisePropertyChanged("table");
            }
        }
        
        /// <remarks/>
        public int tableID {
            get {
                return this.tableIDField;
            }
            set {
                this.tableIDField = value;
                this.RaisePropertyChanged("tableID");
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.sansay.com")]
    public partial class replaceResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int retCodeField;
        
        private string msgField;
        
        /// <remarks/>
        public int retCode {
            get {
                return this.retCodeField;
            }
            set {
                this.retCodeField = value;
                this.RaisePropertyChanged("retCode");
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doReplaceLargeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sansay.com", Order=0)]
        public TelcobrightMediation.SansayWs.replaceLargeParams replaceLargeParams;
        
        public doReplaceLargeRequest() {
        }
        
        public doReplaceLargeRequest(TelcobrightMediation.SansayWs.replaceLargeParams replaceLargeParams) {
            this.replaceLargeParams = replaceLargeParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doReplaceLargeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sansay.com", Order=0)]
        public TelcobrightMediation.SansayWs.replaceResult replaceResult;
        
        public doReplaceLargeResponse() {
        }
        
        public doReplaceLargeResponse(TelcobrightMediation.SansayWs.replaceResult replaceResult) {
            this.replaceResult = replaceResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.sansay.com")]
    public partial class deleteParams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string xmlfileField;
        
        private string tableField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string xmlfile {
            get {
                return this.xmlfileField;
            }
            set {
                this.xmlfileField = value;
                this.RaisePropertyChanged("xmlfile");
            }
        }
        
        /// <remarks/>
        public string table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
                this.RaisePropertyChanged("table");
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.sansay.com")]
    public partial class deleteResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int retCodeField;
        
        private string msgField;
        
        /// <remarks/>
        public int retCode {
            get {
                return this.retCodeField;
            }
            set {
                this.retCodeField = value;
                this.RaisePropertyChanged("retCode");
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doDeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sansay.com", Order=0)]
        public TelcobrightMediation.SansayWs.deleteParams deleteParams;
        
        public doDeleteRequest() {
        }
        
        public doDeleteRequest(TelcobrightMediation.SansayWs.deleteParams deleteParams) {
            this.deleteParams = deleteParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doDeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sansay.com", Order=0)]
        public TelcobrightMediation.SansayWs.deleteResult deleteResult;
        
        public doDeleteResponse() {
        }
        
        public doDeleteResponse(TelcobrightMediation.SansayWs.deleteResult deleteResult) {
            this.deleteResult = deleteResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.sansay.com")]
    public partial class deleteLargeParams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] binfileField;
        
        private string tableField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] binfile {
            get {
                return this.binfileField;
            }
            set {
                this.binfileField = value;
                this.RaisePropertyChanged("binfile");
            }
        }
        
        /// <remarks/>
        public string table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
                this.RaisePropertyChanged("table");
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doDeleteLargeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sansay.com", Order=0)]
        public TelcobrightMediation.SansayWs.deleteLargeParams deleteLargeParams;
        
        public doDeleteLargeRequest() {
        }
        
        public doDeleteLargeRequest(TelcobrightMediation.SansayWs.deleteLargeParams deleteLargeParams) {
            this.deleteLargeParams = deleteLargeParams;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.sansay.com")]
    public partial class updateParams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string xmlfileField;
        
        private string tableField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string xmlfile {
            get {
                return this.xmlfileField;
            }
            set {
                this.xmlfileField = value;
                this.RaisePropertyChanged("xmlfile");
            }
        }
        
        /// <remarks/>
        public string table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
                this.RaisePropertyChanged("table");
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.sansay.com")]
    public partial class updateResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int retCodeField;
        
        private string msgField;
        
        /// <remarks/>
        public int retCode {
            get {
                return this.retCodeField;
            }
            set {
                this.retCodeField = value;
                this.RaisePropertyChanged("retCode");
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sansay.com", Order=0)]
        public TelcobrightMediation.SansayWs.updateParams updateParams;
        
        public doUpdateRequest() {
        }
        
        public doUpdateRequest(TelcobrightMediation.SansayWs.updateParams updateParams) {
            this.updateParams = updateParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sansay.com", Order=0)]
        public TelcobrightMediation.SansayWs.updateResult updateResult;
        
        public doUpdateResponse() {
        }
        
        public doUpdateResponse(TelcobrightMediation.SansayWs.updateResult updateResult) {
            this.updateResult = updateResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.sansay.com")]
    public partial class updateLargeParams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] binfileField;
        
        private string tableField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] binfile {
            get {
                return this.binfileField;
            }
            set {
                this.binfileField = value;
                this.RaisePropertyChanged("binfile");
            }
        }
        
        /// <remarks/>
        public string table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
                this.RaisePropertyChanged("table");
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doUpdateLargeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sansay.com", Order=0)]
        public TelcobrightMediation.SansayWs.updateLargeParams updateLargeParams;
        
        public doUpdateLargeRequest() {
        }
        
        public doUpdateLargeRequest(TelcobrightMediation.SansayWs.updateLargeParams updateLargeParams) {
            this.updateLargeParams = updateLargeParams;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.sansay.com")]
    public partial class downloadParams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tableField;
        
        private string usernameField;
        
        private string passwordField;
        
        private int pageField;
        
        /// <remarks/>
        public string table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
                this.RaisePropertyChanged("table");
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        public int page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
                this.RaisePropertyChanged("page");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.sansay.com")]
    public partial class downloadResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int retCodeField;
        
        private string msgField;
        
        private string xmlfileField;
        
        private int hasMoreField;
        
        /// <remarks/>
        public int retCode {
            get {
                return this.retCodeField;
            }
            set {
                this.retCodeField = value;
                this.RaisePropertyChanged("retCode");
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        /// <remarks/>
        public string xmlfile {
            get {
                return this.xmlfileField;
            }
            set {
                this.xmlfileField = value;
                this.RaisePropertyChanged("xmlfile");
            }
        }
        
        /// <remarks/>
        public int hasMore {
            get {
                return this.hasMoreField;
            }
            set {
                this.hasMoreField = value;
                this.RaisePropertyChanged("hasMore");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doDownloadXmlFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sansay.com", Order=0)]
        public TelcobrightMediation.SansayWs.downloadParams downloadParams;
        
        public doDownloadXmlFileRequest() {
        }
        
        public doDownloadXmlFileRequest(TelcobrightMediation.SansayWs.downloadParams downloadParams) {
            this.downloadParams = downloadParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doDownloadXmlFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sansay.com", Order=0)]
        public TelcobrightMediation.SansayWs.downloadResult downloadResult;
        
        public doDownloadXmlFileResponse() {
        }
        
        public doDownloadXmlFileResponse(TelcobrightMediation.SansayWs.downloadResult downloadResult) {
            this.downloadResult = downloadResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.sansay.com")]
    public partial class downloadLargeParams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tableField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
                this.RaisePropertyChanged("table");
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.sansay.com")]
    public partial class downloadLargeResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int retCodeField;
        
        private string msgField;
        
        private byte[] binfileField;
        
        /// <remarks/>
        public int retCode {
            get {
                return this.retCodeField;
            }
            set {
                this.retCodeField = value;
                this.RaisePropertyChanged("retCode");
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] binfile {
            get {
                return this.binfileField;
            }
            set {
                this.binfileField = value;
                this.RaisePropertyChanged("binfile");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doDownloadLargeXmlFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sansay.com", Order=0)]
        public TelcobrightMediation.SansayWs.downloadLargeParams downloadLargeParams;
        
        public doDownloadLargeXmlFileRequest() {
        }
        
        public doDownloadLargeXmlFileRequest(TelcobrightMediation.SansayWs.downloadLargeParams downloadLargeParams) {
            this.downloadLargeParams = downloadLargeParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doDownloadLargeXmlFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sansay.com", Order=0)]
        public TelcobrightMediation.SansayWs.downloadLargeResult downloadLargeResult;
        
        public doDownloadLargeXmlFileResponse() {
        }
        
        public doDownloadLargeXmlFileResponse(TelcobrightMediation.SansayWs.downloadLargeResult downloadLargeResult) {
            this.downloadLargeResult = downloadLargeResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.sansay.com")]
    public partial class queryParams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tableField;
        
        private string usernameField;
        
        private string passwordField;
        
        private int pageField;
        
        private string queryStringField;
        
        /// <remarks/>
        public string table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
                this.RaisePropertyChanged("table");
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        public int page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
                this.RaisePropertyChanged("page");
            }
        }
        
        /// <remarks/>
        public string queryString {
            get {
                return this.queryStringField;
            }
            set {
                this.queryStringField = value;
                this.RaisePropertyChanged("queryString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.sansay.com")]
    public partial class queryResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int retCodeField;
        
        private string msgField;
        
        private string xmlfileField;
        
        private int hasMoreField;
        
        /// <remarks/>
        public int retCode {
            get {
                return this.retCodeField;
            }
            set {
                this.retCodeField = value;
                this.RaisePropertyChanged("retCode");
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        /// <remarks/>
        public string xmlfile {
            get {
                return this.xmlfileField;
            }
            set {
                this.xmlfileField = value;
                this.RaisePropertyChanged("xmlfile");
            }
        }
        
        /// <remarks/>
        public int hasMore {
            get {
                return this.hasMoreField;
            }
            set {
                this.hasMoreField = value;
                this.RaisePropertyChanged("hasMore");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doQueryXmlFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sansay.com", Order=0)]
        public TelcobrightMediation.SansayWs.queryParams queryParams;
        
        public doQueryXmlFileRequest() {
        }
        
        public doQueryXmlFileRequest(TelcobrightMediation.SansayWs.queryParams queryParams) {
            this.queryParams = queryParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doQueryXmlFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sansay.com", Order=0)]
        public TelcobrightMediation.SansayWs.queryResult queryResult;
        
        public doQueryXmlFileResponse() {
        }
        
        public doQueryXmlFileResponse(TelcobrightMediation.SansayWs.queryResult queryResult) {
            this.queryResult = queryResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.sansay.com")]
    public partial class routelookupParams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string queryStringField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        public string queryString {
            get {
                return this.queryStringField;
            }
            set {
                this.queryStringField = value;
                this.RaisePropertyChanged("queryString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.sansay.com")]
    public partial class routelookupResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int retCodeField;
        
        private string msgField;
        
        private string xmlfileField;
        
        /// <remarks/>
        public int retCode {
            get {
                return this.retCodeField;
            }
            set {
                this.retCodeField = value;
                this.RaisePropertyChanged("retCode");
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        /// <remarks/>
        public string xmlfile {
            get {
                return this.xmlfileField;
            }
            set {
                this.xmlfileField = value;
                this.RaisePropertyChanged("xmlfile");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doRouteLookupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sansay.com", Order=0)]
        public TelcobrightMediation.SansayWs.routelookupParams routelookupParams;
        
        public doRouteLookupRequest() {
        }
        
        public doRouteLookupRequest(TelcobrightMediation.SansayWs.routelookupParams routelookupParams) {
            this.routelookupParams = routelookupParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doRouteLookupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sansay.com", Order=0)]
        public TelcobrightMediation.SansayWs.routelookupResult routelookupResult;
        
        public doRouteLookupResponse() {
        }
        
        public doRouteLookupResponse(TelcobrightMediation.SansayWs.routelookupResult routelookupResult) {
            this.routelookupResult = routelookupResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.sansay.com")]
    public partial class realTimeStatsParams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string statNameField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        public string statName {
            get {
                return this.statNameField;
            }
            set {
                this.statNameField = value;
                this.RaisePropertyChanged("statName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.sansay.com")]
    public partial class realTimeStatsResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int retCodeField;
        
        private string msgField;
        
        private string xmlfileField;
        
        /// <remarks/>
        public int retCode {
            get {
                return this.retCodeField;
            }
            set {
                this.retCodeField = value;
                this.RaisePropertyChanged("retCode");
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        /// <remarks/>
        public string xmlfile {
            get {
                return this.xmlfileField;
            }
            set {
                this.xmlfileField = value;
                this.RaisePropertyChanged("xmlfile");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doRealTimeStatsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sansay.com", Order=0)]
        public TelcobrightMediation.SansayWs.realTimeStatsParams realTimeStatsParams;
        
        public doRealTimeStatsRequest() {
        }
        
        public doRealTimeStatsRequest(TelcobrightMediation.SansayWs.realTimeStatsParams realTimeStatsParams) {
            this.realTimeStatsParams = realTimeStatsParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doRealTimeStatsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sansay.com", Order=0)]
        public TelcobrightMediation.SansayWs.realTimeStatsResult realTimeStatsResult;
        
        public doRealTimeStatsResponse() {
        }
        
        public doRealTimeStatsResponse(TelcobrightMediation.SansayWs.realTimeStatsResult realTimeStatsResult) {
            this.realTimeStatsResult = realTimeStatsResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.sansay.com")]
    public partial class SystemStatsParams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string sysStatNameField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        public string sysStatName {
            get {
                return this.sysStatNameField;
            }
            set {
                this.sysStatNameField = value;
                this.RaisePropertyChanged("sysStatName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.sansay.com")]
    public partial class SystemStatsResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int retCodeField;
        
        private string msgField;
        
        private string xmlfileField;
        
        /// <remarks/>
        public int retCode {
            get {
                return this.retCodeField;
            }
            set {
                this.retCodeField = value;
                this.RaisePropertyChanged("retCode");
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        /// <remarks/>
        public string xmlfile {
            get {
                return this.xmlfileField;
            }
            set {
                this.xmlfileField = value;
                this.RaisePropertyChanged("xmlfile");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSystemStatsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sansay.com", Order=0)]
        public TelcobrightMediation.SansayWs.SystemStatsParams SystemStatsParams;
        
        public doSystemStatsRequest() {
        }
        
        public doSystemStatsRequest(TelcobrightMediation.SansayWs.SystemStatsParams SystemStatsParams) {
            this.SystemStatsParams = SystemStatsParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSystemStatsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sansay.com", Order=0)]
        public TelcobrightMediation.SansayWs.SystemStatsResult SystemStatsResult;
        
        public doSystemStatsResponse() {
        }
        
        public doSystemStatsResponse(TelcobrightMediation.SansayWs.SystemStatsResult SystemStatsResult) {
            this.SystemStatsResult = SystemStatsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SansayWSChannel : TelcobrightMediation.SansayWs.SansayWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SansayWSClient : System.ServiceModel.ClientBase<TelcobrightMediation.SansayWs.SansayWS>, TelcobrightMediation.SansayWs.SansayWS {
        
        public SansayWSClient() {
        }
        
        public SansayWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SansayWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SansayWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SansayWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TelcobrightMediation.SansayWs.doUploadXmlFileResponse TelcobrightMediation.SansayWs.SansayWS.doUploadXmlFile(TelcobrightMediation.SansayWs.doUploadXmlFileRequest request) {
            return base.Channel.doUploadXmlFile(request);
        }
        
        public TelcobrightMediation.SansayWs.uploadResult doUploadXmlFile(TelcobrightMediation.SansayWs.uploadParams uploadParams) {
            TelcobrightMediation.SansayWs.doUploadXmlFileRequest inValue = new TelcobrightMediation.SansayWs.doUploadXmlFileRequest();
            inValue.uploadParams = uploadParams;
            TelcobrightMediation.SansayWs.doUploadXmlFileResponse retVal = ((TelcobrightMediation.SansayWs.SansayWS)(this)).doUploadXmlFile(inValue);
            return retVal.uploadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doUploadXmlFileResponse> TelcobrightMediation.SansayWs.SansayWS.doUploadXmlFileAsync(TelcobrightMediation.SansayWs.doUploadXmlFileRequest request) {
            return base.Channel.doUploadXmlFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doUploadXmlFileResponse> doUploadXmlFileAsync(TelcobrightMediation.SansayWs.uploadParams uploadParams) {
            TelcobrightMediation.SansayWs.doUploadXmlFileRequest inValue = new TelcobrightMediation.SansayWs.doUploadXmlFileRequest();
            inValue.uploadParams = uploadParams;
            return ((TelcobrightMediation.SansayWs.SansayWS)(this)).doUploadXmlFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TelcobrightMediation.SansayWs.doReplaceLargeResponse TelcobrightMediation.SansayWs.SansayWS.doReplaceLarge(TelcobrightMediation.SansayWs.doReplaceLargeRequest request) {
            return base.Channel.doReplaceLarge(request);
        }
        
        public TelcobrightMediation.SansayWs.replaceResult doReplaceLarge(TelcobrightMediation.SansayWs.replaceLargeParams replaceLargeParams) {
            TelcobrightMediation.SansayWs.doReplaceLargeRequest inValue = new TelcobrightMediation.SansayWs.doReplaceLargeRequest();
            inValue.replaceLargeParams = replaceLargeParams;
            TelcobrightMediation.SansayWs.doReplaceLargeResponse retVal = ((TelcobrightMediation.SansayWs.SansayWS)(this)).doReplaceLarge(inValue);
            return retVal.replaceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doReplaceLargeResponse> TelcobrightMediation.SansayWs.SansayWS.doReplaceLargeAsync(TelcobrightMediation.SansayWs.doReplaceLargeRequest request) {
            return base.Channel.doReplaceLargeAsync(request);
        }
        
        public System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doReplaceLargeResponse> doReplaceLargeAsync(TelcobrightMediation.SansayWs.replaceLargeParams replaceLargeParams) {
            TelcobrightMediation.SansayWs.doReplaceLargeRequest inValue = new TelcobrightMediation.SansayWs.doReplaceLargeRequest();
            inValue.replaceLargeParams = replaceLargeParams;
            return ((TelcobrightMediation.SansayWs.SansayWS)(this)).doReplaceLargeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TelcobrightMediation.SansayWs.doDeleteResponse TelcobrightMediation.SansayWs.SansayWS.doDelete(TelcobrightMediation.SansayWs.doDeleteRequest request) {
            return base.Channel.doDelete(request);
        }
        
        public TelcobrightMediation.SansayWs.deleteResult doDelete(TelcobrightMediation.SansayWs.deleteParams deleteParams) {
            TelcobrightMediation.SansayWs.doDeleteRequest inValue = new TelcobrightMediation.SansayWs.doDeleteRequest();
            inValue.deleteParams = deleteParams;
            TelcobrightMediation.SansayWs.doDeleteResponse retVal = ((TelcobrightMediation.SansayWs.SansayWS)(this)).doDelete(inValue);
            return retVal.deleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doDeleteResponse> TelcobrightMediation.SansayWs.SansayWS.doDeleteAsync(TelcobrightMediation.SansayWs.doDeleteRequest request) {
            return base.Channel.doDeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doDeleteResponse> doDeleteAsync(TelcobrightMediation.SansayWs.deleteParams deleteParams) {
            TelcobrightMediation.SansayWs.doDeleteRequest inValue = new TelcobrightMediation.SansayWs.doDeleteRequest();
            inValue.deleteParams = deleteParams;
            return ((TelcobrightMediation.SansayWs.SansayWS)(this)).doDeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TelcobrightMediation.SansayWs.doDeleteResponse TelcobrightMediation.SansayWs.SansayWS.doDeleteLarge(TelcobrightMediation.SansayWs.doDeleteLargeRequest request) {
            return base.Channel.doDeleteLarge(request);
        }
        
        public TelcobrightMediation.SansayWs.deleteResult doDeleteLarge(TelcobrightMediation.SansayWs.deleteLargeParams deleteLargeParams) {
            TelcobrightMediation.SansayWs.doDeleteLargeRequest inValue = new TelcobrightMediation.SansayWs.doDeleteLargeRequest();
            inValue.deleteLargeParams = deleteLargeParams;
            TelcobrightMediation.SansayWs.doDeleteResponse retVal = ((TelcobrightMediation.SansayWs.SansayWS)(this)).doDeleteLarge(inValue);
            return retVal.deleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doDeleteResponse> TelcobrightMediation.SansayWs.SansayWS.doDeleteLargeAsync(TelcobrightMediation.SansayWs.doDeleteLargeRequest request) {
            return base.Channel.doDeleteLargeAsync(request);
        }
        
        public System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doDeleteResponse> doDeleteLargeAsync(TelcobrightMediation.SansayWs.deleteLargeParams deleteLargeParams) {
            TelcobrightMediation.SansayWs.doDeleteLargeRequest inValue = new TelcobrightMediation.SansayWs.doDeleteLargeRequest();
            inValue.deleteLargeParams = deleteLargeParams;
            return ((TelcobrightMediation.SansayWs.SansayWS)(this)).doDeleteLargeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TelcobrightMediation.SansayWs.doUpdateResponse TelcobrightMediation.SansayWs.SansayWS.doUpdate(TelcobrightMediation.SansayWs.doUpdateRequest request) {
            return base.Channel.doUpdate(request);
        }
        
        public TelcobrightMediation.SansayWs.updateResult doUpdate(TelcobrightMediation.SansayWs.updateParams updateParams) {
            TelcobrightMediation.SansayWs.doUpdateRequest inValue = new TelcobrightMediation.SansayWs.doUpdateRequest();
            inValue.updateParams = updateParams;
            TelcobrightMediation.SansayWs.doUpdateResponse retVal = ((TelcobrightMediation.SansayWs.SansayWS)(this)).doUpdate(inValue);
            return retVal.updateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doUpdateResponse> TelcobrightMediation.SansayWs.SansayWS.doUpdateAsync(TelcobrightMediation.SansayWs.doUpdateRequest request) {
            return base.Channel.doUpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doUpdateResponse> doUpdateAsync(TelcobrightMediation.SansayWs.updateParams updateParams) {
            TelcobrightMediation.SansayWs.doUpdateRequest inValue = new TelcobrightMediation.SansayWs.doUpdateRequest();
            inValue.updateParams = updateParams;
            return ((TelcobrightMediation.SansayWs.SansayWS)(this)).doUpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TelcobrightMediation.SansayWs.doUpdateResponse TelcobrightMediation.SansayWs.SansayWS.doUpdateLarge(TelcobrightMediation.SansayWs.doUpdateLargeRequest request) {
            return base.Channel.doUpdateLarge(request);
        }
        
        public TelcobrightMediation.SansayWs.updateResult doUpdateLarge(TelcobrightMediation.SansayWs.updateLargeParams updateLargeParams) {
            TelcobrightMediation.SansayWs.doUpdateLargeRequest inValue = new TelcobrightMediation.SansayWs.doUpdateLargeRequest();
            inValue.updateLargeParams = updateLargeParams;
            TelcobrightMediation.SansayWs.doUpdateResponse retVal = ((TelcobrightMediation.SansayWs.SansayWS)(this)).doUpdateLarge(inValue);
            return retVal.updateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doUpdateResponse> TelcobrightMediation.SansayWs.SansayWS.doUpdateLargeAsync(TelcobrightMediation.SansayWs.doUpdateLargeRequest request) {
            return base.Channel.doUpdateLargeAsync(request);
        }
        
        public System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doUpdateResponse> doUpdateLargeAsync(TelcobrightMediation.SansayWs.updateLargeParams updateLargeParams) {
            TelcobrightMediation.SansayWs.doUpdateLargeRequest inValue = new TelcobrightMediation.SansayWs.doUpdateLargeRequest();
            inValue.updateLargeParams = updateLargeParams;
            return ((TelcobrightMediation.SansayWs.SansayWS)(this)).doUpdateLargeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TelcobrightMediation.SansayWs.doDownloadXmlFileResponse TelcobrightMediation.SansayWs.SansayWS.doDownloadXmlFile(TelcobrightMediation.SansayWs.doDownloadXmlFileRequest request) {
            return base.Channel.doDownloadXmlFile(request);
        }
        
        public TelcobrightMediation.SansayWs.downloadResult doDownloadXmlFile(TelcobrightMediation.SansayWs.downloadParams downloadParams) {
            TelcobrightMediation.SansayWs.doDownloadXmlFileRequest inValue = new TelcobrightMediation.SansayWs.doDownloadXmlFileRequest();
            inValue.downloadParams = downloadParams;
            TelcobrightMediation.SansayWs.doDownloadXmlFileResponse retVal = ((TelcobrightMediation.SansayWs.SansayWS)(this)).doDownloadXmlFile(inValue);
            return retVal.downloadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doDownloadXmlFileResponse> TelcobrightMediation.SansayWs.SansayWS.doDownloadXmlFileAsync(TelcobrightMediation.SansayWs.doDownloadXmlFileRequest request) {
            return base.Channel.doDownloadXmlFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doDownloadXmlFileResponse> doDownloadXmlFileAsync(TelcobrightMediation.SansayWs.downloadParams downloadParams) {
            TelcobrightMediation.SansayWs.doDownloadXmlFileRequest inValue = new TelcobrightMediation.SansayWs.doDownloadXmlFileRequest();
            inValue.downloadParams = downloadParams;
            return ((TelcobrightMediation.SansayWs.SansayWS)(this)).doDownloadXmlFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TelcobrightMediation.SansayWs.doDownloadLargeXmlFileResponse TelcobrightMediation.SansayWs.SansayWS.doDownloadLargeXmlFile(TelcobrightMediation.SansayWs.doDownloadLargeXmlFileRequest request) {
            return base.Channel.doDownloadLargeXmlFile(request);
        }
        
        public TelcobrightMediation.SansayWs.downloadLargeResult doDownloadLargeXmlFile(TelcobrightMediation.SansayWs.downloadLargeParams downloadLargeParams) {
            TelcobrightMediation.SansayWs.doDownloadLargeXmlFileRequest inValue = new TelcobrightMediation.SansayWs.doDownloadLargeXmlFileRequest();
            inValue.downloadLargeParams = downloadLargeParams;
            TelcobrightMediation.SansayWs.doDownloadLargeXmlFileResponse retVal = ((TelcobrightMediation.SansayWs.SansayWS)(this)).doDownloadLargeXmlFile(inValue);
            return retVal.downloadLargeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doDownloadLargeXmlFileResponse> TelcobrightMediation.SansayWs.SansayWS.doDownloadLargeXmlFileAsync(TelcobrightMediation.SansayWs.doDownloadLargeXmlFileRequest request) {
            return base.Channel.doDownloadLargeXmlFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doDownloadLargeXmlFileResponse> doDownloadLargeXmlFileAsync(TelcobrightMediation.SansayWs.downloadLargeParams downloadLargeParams) {
            TelcobrightMediation.SansayWs.doDownloadLargeXmlFileRequest inValue = new TelcobrightMediation.SansayWs.doDownloadLargeXmlFileRequest();
            inValue.downloadLargeParams = downloadLargeParams;
            return ((TelcobrightMediation.SansayWs.SansayWS)(this)).doDownloadLargeXmlFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TelcobrightMediation.SansayWs.doQueryXmlFileResponse TelcobrightMediation.SansayWs.SansayWS.doQueryXmlFile(TelcobrightMediation.SansayWs.doQueryXmlFileRequest request) {
            return base.Channel.doQueryXmlFile(request);
        }
        
        public TelcobrightMediation.SansayWs.queryResult doQueryXmlFile(TelcobrightMediation.SansayWs.queryParams queryParams) {
            TelcobrightMediation.SansayWs.doQueryXmlFileRequest inValue = new TelcobrightMediation.SansayWs.doQueryXmlFileRequest();
            inValue.queryParams = queryParams;
            TelcobrightMediation.SansayWs.doQueryXmlFileResponse retVal = ((TelcobrightMediation.SansayWs.SansayWS)(this)).doQueryXmlFile(inValue);
            return retVal.queryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doQueryXmlFileResponse> TelcobrightMediation.SansayWs.SansayWS.doQueryXmlFileAsync(TelcobrightMediation.SansayWs.doQueryXmlFileRequest request) {
            return base.Channel.doQueryXmlFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doQueryXmlFileResponse> doQueryXmlFileAsync(TelcobrightMediation.SansayWs.queryParams queryParams) {
            TelcobrightMediation.SansayWs.doQueryXmlFileRequest inValue = new TelcobrightMediation.SansayWs.doQueryXmlFileRequest();
            inValue.queryParams = queryParams;
            return ((TelcobrightMediation.SansayWs.SansayWS)(this)).doQueryXmlFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TelcobrightMediation.SansayWs.doRouteLookupResponse TelcobrightMediation.SansayWs.SansayWS.doRouteLookup(TelcobrightMediation.SansayWs.doRouteLookupRequest request) {
            return base.Channel.doRouteLookup(request);
        }
        
        public TelcobrightMediation.SansayWs.routelookupResult doRouteLookup(TelcobrightMediation.SansayWs.routelookupParams routelookupParams) {
            TelcobrightMediation.SansayWs.doRouteLookupRequest inValue = new TelcobrightMediation.SansayWs.doRouteLookupRequest();
            inValue.routelookupParams = routelookupParams;
            TelcobrightMediation.SansayWs.doRouteLookupResponse retVal = ((TelcobrightMediation.SansayWs.SansayWS)(this)).doRouteLookup(inValue);
            return retVal.routelookupResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doRouteLookupResponse> TelcobrightMediation.SansayWs.SansayWS.doRouteLookupAsync(TelcobrightMediation.SansayWs.doRouteLookupRequest request) {
            return base.Channel.doRouteLookupAsync(request);
        }
        
        public System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doRouteLookupResponse> doRouteLookupAsync(TelcobrightMediation.SansayWs.routelookupParams routelookupParams) {
            TelcobrightMediation.SansayWs.doRouteLookupRequest inValue = new TelcobrightMediation.SansayWs.doRouteLookupRequest();
            inValue.routelookupParams = routelookupParams;
            return ((TelcobrightMediation.SansayWs.SansayWS)(this)).doRouteLookupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TelcobrightMediation.SansayWs.doRealTimeStatsResponse TelcobrightMediation.SansayWs.SansayWS.doRealTimeStats(TelcobrightMediation.SansayWs.doRealTimeStatsRequest request) {
            return base.Channel.doRealTimeStats(request);
        }
        
        public TelcobrightMediation.SansayWs.realTimeStatsResult doRealTimeStats(TelcobrightMediation.SansayWs.realTimeStatsParams realTimeStatsParams) {
            TelcobrightMediation.SansayWs.doRealTimeStatsRequest inValue = new TelcobrightMediation.SansayWs.doRealTimeStatsRequest();
            inValue.realTimeStatsParams = realTimeStatsParams;
            TelcobrightMediation.SansayWs.doRealTimeStatsResponse retVal = ((TelcobrightMediation.SansayWs.SansayWS)(this)).doRealTimeStats(inValue);
            return retVal.realTimeStatsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doRealTimeStatsResponse> TelcobrightMediation.SansayWs.SansayWS.doRealTimeStatsAsync(TelcobrightMediation.SansayWs.doRealTimeStatsRequest request) {
            return base.Channel.doRealTimeStatsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doRealTimeStatsResponse> doRealTimeStatsAsync(TelcobrightMediation.SansayWs.realTimeStatsParams realTimeStatsParams) {
            TelcobrightMediation.SansayWs.doRealTimeStatsRequest inValue = new TelcobrightMediation.SansayWs.doRealTimeStatsRequest();
            inValue.realTimeStatsParams = realTimeStatsParams;
            return ((TelcobrightMediation.SansayWs.SansayWS)(this)).doRealTimeStatsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TelcobrightMediation.SansayWs.doSystemStatsResponse TelcobrightMediation.SansayWs.SansayWS.doSystemStats(TelcobrightMediation.SansayWs.doSystemStatsRequest request) {
            return base.Channel.doSystemStats(request);
        }
        
        public TelcobrightMediation.SansayWs.SystemStatsResult doSystemStats(TelcobrightMediation.SansayWs.SystemStatsParams SystemStatsParams) {
            TelcobrightMediation.SansayWs.doSystemStatsRequest inValue = new TelcobrightMediation.SansayWs.doSystemStatsRequest();
            inValue.SystemStatsParams = SystemStatsParams;
            TelcobrightMediation.SansayWs.doSystemStatsResponse retVal = ((TelcobrightMediation.SansayWs.SansayWS)(this)).doSystemStats(inValue);
            return retVal.SystemStatsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doSystemStatsResponse> TelcobrightMediation.SansayWs.SansayWS.doSystemStatsAsync(TelcobrightMediation.SansayWs.doSystemStatsRequest request) {
            return base.Channel.doSystemStatsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TelcobrightMediation.SansayWs.doSystemStatsResponse> doSystemStatsAsync(TelcobrightMediation.SansayWs.SystemStatsParams SystemStatsParams) {
            TelcobrightMediation.SansayWs.doSystemStatsRequest inValue = new TelcobrightMediation.SansayWs.doSystemStatsRequest();
            inValue.SystemStatsParams = SystemStatsParams;
            return ((TelcobrightMediation.SansayWs.SansayWS)(this)).doSystemStatsAsync(inValue);
        }
    }
}
