//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_action
    {
        public long id { get; set; }
        public long idAccount { get; set; }
        public decimal threshhold_value { get; set; }
        public long idAccountAction { get; set; }
    
        public virtual account account { get; set; }
    }
}
