//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public account()
        {
            this.acc_action = new HashSet<acc_action>();
            this.invoices = new HashSet<invoice>();
        }
    
        public long id { get; set; }
        public Nullable<long> idParent { get; set; }
        public string idParentExternal { get; set; }
        public int idPartner { get; set; }
        public string accountName { get; set; }
        public int serviceGroup { get; set; }
        public int serviceFamily { get; set; }
        public int product { get; set; }
        public string billableType { get; set; }
        public string uom { get; set; }
        public int Depth { get; set; }
        public string Lineage { get; set; }
        public string remark { get; set; }
        public Nullable<sbyte> isBillable { get; set; }
        public Nullable<sbyte> isCustomerAccount { get; set; }
        public Nullable<sbyte> isSupplierAccount { get; set; }
        public decimal balanceBefore { get; set; }
        public Nullable<decimal> lastAmount { get; set; }
        public decimal balanceAfter { get; set; }
        public System.DateTime lastUpdated { get; set; }
        public Nullable<int> superviseNegativeBalance { get; set; }
        public decimal negativeBalanceLimit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acc_action> acc_action { get; set; }
        public virtual partner partner { get; set; }
        public virtual partner partner1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice> invoices { get; set; }
    }
}
