//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bridgedroute
    {
        public int id { get; set; }
        public int idSwitch { get; set; }
        public string tgName { get; set; }
        public int inPartner { get; set; }
        public int outPartner { get; set; }
        public Nullable<int> nationalOrInternational { get; set; }
    
        public virtual partner partner { get; set; }
        public virtual partner partner1 { get; set; }
        public virtual ne ne { get; set; }
    }
}
