//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdr
    {
        public int SwitchId { get; set; }
        public long idcall { get; set; }
        public long SequenceNumber { get; set; }
        public string FileName { get; set; }
        public int ServiceGroup { get; set; }
        public string incomingroute { get; set; }
        public string OriginatingIP { get; set; }
        public Nullable<int> OPC { get; set; }
        public Nullable<int> OriginatingCIC { get; set; }
        public string OriginatingCalledNumber { get; set; }
        public string TerminatingCalledNumber { get; set; }
        public string OriginatingCallingNumber { get; set; }
        public string TerminatingCallingNumber { get; set; }
        public Nullable<int> PrePaid { get; set; }
        public decimal DurationSec { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<System.DateTime> ConnectTime { get; set; }
        public Nullable<System.DateTime> AnswerTime { get; set; }
        public Nullable<int> ChargingStatus { get; set; }
        public Nullable<float> PDD { get; set; }
        public string CountryCode { get; set; }
        public string AreaCodeOrLata { get; set; }
        public Nullable<int> ReleaseDirection { get; set; }
        public Nullable<int> ReleaseCauseSystem { get; set; }
        public Nullable<int> ReleaseCauseEgress { get; set; }
        public string outgoingroute { get; set; }
        public string TerminatingIP { get; set; }
        public Nullable<int> DPC { get; set; }
        public Nullable<int> TerminatingCIC { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<int> inPartnerId { get; set; }
        public Nullable<decimal> CustomerRate { get; set; }
        public Nullable<int> outPartnerId { get; set; }
        public Nullable<decimal> SupplierRate { get; set; }
        public string MatchedPrefixY { get; set; }
        public Nullable<decimal> USDRateY { get; set; }
        public string matchedprefixcustomer { get; set; }
        public string matchedprefixsupplier { get; set; }
        public Nullable<decimal> CustomerCost { get; set; }
        public Nullable<decimal> SupplierCost { get; set; }
        public Nullable<decimal> CostANSIn { get; set; }
        public Nullable<decimal> CostICXIn { get; set; }
        public Nullable<decimal> Tax1 { get; set; }
        public Nullable<decimal> IGWRevenueIn { get; set; }
        public Nullable<decimal> RevenueANSOut { get; set; }
        public Nullable<decimal> RevenueIGWOut { get; set; }
        public Nullable<decimal> RevenueICXOut { get; set; }
        public Nullable<decimal> Tax2 { get; set; }
        public Nullable<decimal> SubscriberChargeXOut { get; set; }
        public Nullable<decimal> CarrierCostYIGWOut { get; set; }
        public string ANSPrefixOrig { get; set; }
        public Nullable<int> AnsIdOrig { get; set; }
        public string AnsPrefixTerm { get; set; }
        public Nullable<int> AnsIdTerm { get; set; }
        public Nullable<int> validflag { get; set; }
        public Nullable<int> PartialFlag { get; set; }
        public Nullable<int> releasecauseingress { get; set; }
        public Nullable<long> CustomerCallNumberANS { get; set; }
        public Nullable<long> SupplierCallNumberANS { get; set; }
        public Nullable<int> CalledPartyNOA { get; set; }
        public Nullable<int> CallingPartyNOA { get; set; }
        public string AdditionalSystemCodes { get; set; }
        public string AdditionalPartyNumber { get; set; }
        public string ResellerIds { get; set; }
        public Nullable<decimal> BTRCTermRate { get; set; }
        public string PreviousRoutes { get; set; }
        public Nullable<int> E1Id { get; set; }
        public string MediaIP1 { get; set; }
        public string MediaIP2 { get; set; }
        public string MediaIP3 { get; set; }
        public string MediaIP4 { get; set; }
        public Nullable<decimal> CallCancelDuration { get; set; }
        public Nullable<int> E1IdOut { get; set; }
        public string inTrunkAdditionalInfo { get; set; }
        public string outTrunkAdditionalInfo { get; set; }
        public string inMgwId { get; set; }
        public string outMgwId { get; set; }
        public Nullable<int> mediationcomplete { get; set; }
        public string codec { get; set; }
        public Nullable<int> ConnectedNumberType { get; set; }
        public string RedirectingNumber { get; set; }
        public Nullable<int> CallForwardOrRoamingType { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public Nullable<int> field1 { get; set; }
        public Nullable<int> field2 { get; set; }
        public Nullable<int> field3 { get; set; }
        public string errorCode { get; set; }
        public Nullable<int> field5 { get; set; }
        public Nullable<decimal> roundedduration { get; set; }
        public Nullable<decimal> PartialDuration { get; set; }
        public Nullable<System.DateTime> PartialAnswerTime { get; set; }
        public Nullable<System.DateTime> PartialEndTime { get; set; }
        public Nullable<long> FinalRecord { get; set; }
        public Nullable<decimal> Duration1 { get; set; }
        public Nullable<decimal> Duration2 { get; set; }
        public Nullable<decimal> Duration3 { get; set; }
        public Nullable<decimal> Duration4 { get; set; }
        public Nullable<int> PreviousPeriodCdr { get; set; }
        public string UniqueBillId { get; set; }
        public string AdditionalMetaData { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> SubCategory { get; set; }
        public Nullable<long> ChangedByJobId { get; set; }
        public System.DateTime ActualStartTime { get; set; }
    }
}
