//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdrfieldlist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cdrfieldlist()
        {
            this.cdrfieldmappingbyswitchtypes = new HashSet<cdrfieldmappingbyswitchtype>();
        }
    
        public int fieldnumber { get; set; }
        public string FieldName { get; set; }
        public Nullable<int> IsNumeric { get; set; }
        public Nullable<int> IsDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdrfieldmappingbyswitchtype> cdrfieldmappingbyswitchtypes { get; set; }
    }
}
