//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class countrycode
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<float> refasr { get; set; }
        public Nullable<float> refacd { get; set; }
        public Nullable<float> refccr { get; set; }
        public Nullable<float> refccrbycc { get; set; }
        public Nullable<float> refpdd { get; set; }
        public Nullable<float> refasrfas { get; set; }
    }
}
