//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class durationmeta
    {
        public int id { get; set; }
        public string filename { get; set; }
        public Nullable<decimal> oldDuration { get; set; }
        public Nullable<decimal> newDuration { get; set; }
        public Nullable<decimal> durationAfterJob { get; set; }
    }
}
