//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class enumeration
    {
        public string ENUM_ID { get; set; }
        public string ENUM_TYPE_ID { get; set; }
        public string ENUM_CODE { get; set; }
        public string SEQUENCE_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_STAMP { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_TX_STAMP { get; set; }
        public Nullable<System.DateTime> CREATED_STAMP { get; set; }
        public Nullable<System.DateTime> CREATED_TX_STAMP { get; set; }
    }
}
