//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public invoice()
        {
            this.invoice_item = new HashSet<invoice_item>();
        }
    
        public long INVOICE_ID { get; set; }
        public string INVOICE_TYPE_ID { get; set; }
        public string PARTY_ID_FROM { get; set; }
        public string PARTY_ID { get; set; }
        public string ROLE_TYPE_ID { get; set; }
        public string STATUS_ID { get; set; }
        public Nullable<long> BILLING_ACCOUNT_ID { get; set; }
        public string CONTACT_MECH_ID { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public Nullable<System.DateTime> PAID_DATE { get; set; }
        public string INVOICE_MESSAGE { get; set; }
        public string REFERENCE_NUMBER { get; set; }
        public string DESCRIPTION { get; set; }
        public string CURRENCY_UOM_ID { get; set; }
        public string RECURRENCE_INFO_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_STAMP { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_TX_STAMP { get; set; }
        public Nullable<System.DateTime> CREATED_STAMP { get; set; }
        public Nullable<System.DateTime> CREATED_TX_STAMP { get; set; }
    
        public virtual account account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice_item> invoice_item { get; set; }
    }
}
