//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class rateplanassignmenttuple
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rateplanassignmenttuple()
        {
            this.rateassigns = new HashSet<rateassign>();
            this.ratetaskassigns = new HashSet<ratetaskassign>();
        }
    
        public int id { get; set; }
        public int idService { get; set; }
        public int AssignDirection { get; set; }
        public Nullable<int> idpartner { get; set; }
        public Nullable<int> route { get; set; }
        public int priority { get; set; }
    
        public virtual billingruleassignment billingruleassignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rateassign> rateassigns { get; set; }
        public virtual route route1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ratetaskassign> ratetaskassigns { get; set; }
    }
}
