//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class rateassign
    {
        public long id { get; set; }
        public string Prefix { get; set; }
        public string description { get; set; }
        public decimal rateamount { get; set; }
        public int WeekDayStart { get; set; }
        public int WeekDayEnd { get; set; }
        public string starttime { get; set; }
        public string endtime { get; set; }
        public int Resolution { get; set; }
        public float MinDurationSec { get; set; }
        public int SurchargeTime { get; set; }
        public decimal SurchargeAmount { get; set; }
        public Nullable<long> idrateplan { get; set; }
        public string CountryCode { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public Nullable<int> field1 { get; set; }
        public Nullable<int> field2 { get; set; }
        public int field3 { get; set; }
        public string field4 { get; set; }
        public string field5 { get; set; }
        public System.DateTime startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public int Inactive { get; set; }
        public int RouteDisabled { get; set; }
        public int Type { get; set; }
        public int Currency { get; set; }
        public Nullable<float> OtherAmount1 { get; set; }
        public Nullable<float> OtherAmount2 { get; set; }
        public Nullable<float> OtherAmount3 { get; set; }
        public Nullable<decimal> OtherAmount4 { get; set; }
        public Nullable<decimal> OtherAmount5 { get; set; }
        public Nullable<float> OtherAmount6 { get; set; }
        public Nullable<float> OtherAmount7 { get; set; }
        public Nullable<float> OtherAmount8 { get; set; }
        public Nullable<float> OtherAmount9 { get; set; }
        public Nullable<float> OtherAmount10 { get; set; }
        public decimal TimeZoneOffsetSec { get; set; }
        public Nullable<int> RatePosition { get; set; }
        public Nullable<float> IgwPercentageIn { get; set; }
        public string ConflictingRateIds { get; set; }
        public Nullable<long> ChangedByTaskId { get; set; }
        public Nullable<System.DateTime> ChangedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<long> idPreviousRate { get; set; }
        public Nullable<sbyte> EndPreviousRate { get; set; }
        public Nullable<sbyte> Category { get; set; }
        public Nullable<sbyte> SubCategory { get; set; }
        public Nullable<int> ChangeCommitted { get; set; }
        public string ConflictingRates { get; set; }
        public string OverlappingRates { get; set; }
        public string Comment1 { get; set; }
        public string Comment2 { get; set; }
        public string BillingParams { get; set; }
    }
}
