Drop TABLE IF EXISTS `ipaddressorpointcode`;
/*
-- Query: select * , count(routename) from ipaddressorpointcode
group by(routename)
-- Date: 2023-07-19 19:22
*/
CREATE TABLE `ipaddressorpointcode` (
  `idroute` int(11) NOT NULL DEFAULT '0',
  `RouteName` varchar(45) COLLATE utf8mb4_bin NOT NULL,
  `SwitchId` int(11) NOT NULL,
  `CommonRoute` int(11) NOT NULL DEFAULT '0',
  `idPartner` int(11) NOT NULL,
  `NationalOrInternational` int(11) NOT NULL DEFAULT '0',
  `Description` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
  `Status` int(11) NOT NULL DEFAULT '0',
  `date1` datetime DEFAULT NULL,
  `field1` int(11) DEFAULT NULL,
  `field2` int(11) DEFAULT NULL,
  `field3` int(11) DEFAULT NULL,
  `field4` int(11) DEFAULT NULL,
  `field5` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (188,'10.16.94.0/26',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (186,'10.16.94.64/28',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (187,'10.16.95.0/26',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (185,'10.16.95.64/28',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (169,'10.184.199.64/32',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (170,'10.184.199.65/32',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (171,'10.184.199.66/32',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (172,'10.184.199.67/32',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (173,'10.184.199.68/32',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (174,'10.184.199.69/32',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (175,'10.184.199.70/32',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (176,'10.184.199.71/32',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (177,'10.184.199.72/32',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (178,'10.184.199.73/32',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (179,'10.184.199.74/32',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (180,'10.184.199.75/32',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (181,'10.184.199.76/32',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (182,'10.184.199.77/32',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (183,'10.184.199.78/32',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (184,'10.184.199.79/32',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (165,'10.184.199.80/32',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (166,'10.184.199.81/32',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (167,'10.184.199.82/32',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (168,'10.184.199.83/32',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (189,'10.72.240.0/27',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (193,'10.72.240.128/28',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (194,'10.72.240.144/28',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (190,'10.72.240.32/29',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (191,'10.72.240.40/29',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (192,'10.72.240.64/26',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (377,'10579',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (290,'10580',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (278,'10581',0,0,28,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (370,'10582',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (289,'10834',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (288,'12626',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (376,'13010',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (287,'13013',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (224,'14676',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (222,'14677',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (375,'14930',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (223,'14932',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (372,'14933',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (197,'4434',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (251,'4435',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (243,'4437',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (214,'4442',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (291,'4466',0,0,3,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (225,'4467',0,0,2,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (292,'4468',0,0,3,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (357,'4469',0,0,1,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (207,'4540',0,0,68,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (206,'4541',0,0,66,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (210,'4550',0,0,67,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (198,'4562',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (201,'4563',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (242,'4568',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (236,'4570',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (380,'4576',0,0,28,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (216,'4577',0,0,28,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (226,'4587',0,0,1,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (229,'4599',0,0,5,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (204,'4698',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (231,'4710',0,0,6,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (227,'4715',0,0,4,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (228,'4720',0,0,7,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (196,'4818',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (373,'4819',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (237,'4843',0,0,3,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (230,'4844',0,0,3,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (209,'4946',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (205,'5075',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (271,'5202',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (200,'5203',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (359,'5331',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (213,'5459',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (203,'5460',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (306,'5466',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (277,'5587',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (374,'5588',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (208,'5589',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (234,'5594',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (249,'5715',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (199,'5717',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (202,'5722',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (252,'5843',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (232,'6108',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (354,'6109',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (362,'6481',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (217,'6482',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (371,'6484',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (220,'6485',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (221,'6489',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (365,'6490',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (219,'6609',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (364,'6618',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (361,'6737',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (356,'6865',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (355,'6866',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (358,'6869',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (218,'7121',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (263,'8531',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (256,'8532',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (258,'8533',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (257,'8534',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (262,'8535',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (363,'8536',0,0,24,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (366,'8538',0,0,25,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (260,'8658',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (259,'8786',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (378,'8788',0,0,28,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `ipaddressorpointcode` (`idroute`,`RouteName`,`SwitchId`,`CommonRoute`,`idPartner`,`NationalOrInternational`,`Description`,`Status`,`date1`,`field1`,`field2`,`field3`,`field4`,`field5`) VALUES (261,'9042',0,0,23,0,'0',0,NULL,NULL,NULL,NULL,NULL,NULL);
